from __future__ import division
import numpy as np
def ham_first_derivs(m1, m2, q1, q2, q3, p1, p2, p3):
    M = m1+m2
    mu = m1*m2/M
    eta = mu/M
    q = np.sqrt(q1*q1+q2*q2+q3*q3)
    u = 1/q
    psq = p1*p1+p2*p2+p3*p3
    n3 = q3*u
    n2 = q2*u
    n1 = q1*u
    ndotp = n1*p1+n2*p2+n3*p3
    qprime3 = q3
    qprime2 = q2
    qprime1 = q1
    pprime3 = p3
    pprime2 = p2
    pprime1 = p1
    qprimesq = qprime1*qprime1+qprime2*qprime2+qprime3*qprime3
    qprime = np.sqrt(qprimesq)
    uprime = 1/qprime
    nprime3 = qprime3*uprime
    nprime2 = qprime2*uprime
    nprime1 = qprime1*uprime
    pprimedotnprime = pprime1*nprime1+pprime2*nprime2+pprime3*nprime3
    nprimedotpprimesq = pprimedotnprime*pprimedotnprime
    pprimesq = pprime1*pprime1+pprime2*pprime2+pprime3*pprime3
    B = 1+2*uprime+(4-6*eta)*uprime*uprime
    Binv = 1/B
    A = 1-2*uprime+2*eta*uprime*uprime*uprime
    Heff = np.sqrt(A*(1+pprimesq+nprimedotpprimesq*(Binv-1)))
    Hreal = (np.sqrt(1+2*eta*(Heff-1))-1)/eta
    q_prmq1 = q1/np.sqrt(q1**2 + q2**2 + q3**2)
    q_prmq2 = q2/np.sqrt(q1**2 + q2**2 + q3**2)
    q_prmq3 = q3/np.sqrt(q1**2 + q2**2 + q3**2)
    u_prmq1 = -q_prmq1/q**2
    u_prmq2 = -q_prmq2/q**2
    u_prmq3 = -q_prmq3/q**2
    psq_prmp1 = 2*p1
    psq_prmp2 = 2*p2
    psq_prmp3 = 2*p3
    n3_prmq1 = q3*u_prmq1
    n3_prmq2 = q3*u_prmq2
    n3_prmq3 = q3*u_prmq3 + u
    n2_prmq1 = q2*u_prmq1
    n2_prmq2 = q2*u_prmq2 + u
    n2_prmq3 = q2*u_prmq3
    n1_prmq1 = q1*u_prmq1 + u
    n1_prmq2 = q1*u_prmq2
    n1_prmq3 = q1*u_prmq3
    ndotp_prmq1 = n1_prmq1*p1 + n2_prmq1*p2 + n3_prmq1*p3
    ndotp_prmq2 = n1_prmq2*p1 + n2_prmq2*p2 + n3_prmq2*p3
    ndotp_prmq3 = n1_prmq3*p1 + n2_prmq3*p2 + n3_prmq3*p3
    ndotp_prmp1 = n1
    ndotp_prmp2 = n2
    ndotp_prmp3 = n3
    qprime3_prmq3 = 1
    qprime2_prmq2 = 1
    qprime1_prmq1 = 1
    pprime3_prmp3 = 1
    pprime2_prmp2 = 1
    pprime1_prmp1 = 1
    qprimesq_prmq1 = 2*qprime1*qprime1_prmq1
    qprimesq_prmq2 = 2*qprime2*qprime2_prmq2
    qprimesq_prmq3 = 2*qprime3*qprime3_prmq3
    qprime_prmq1 = qprimesq_prmq1/(2*np.sqrt(qprimesq))
    qprime_prmq2 = qprimesq_prmq2/(2*np.sqrt(qprimesq))
    qprime_prmq3 = qprimesq_prmq3/(2*np.sqrt(qprimesq))
    uprime_prmq1 = -qprime_prmq1/qprime**2
    uprime_prmq2 = -qprime_prmq2/qprime**2
    uprime_prmq3 = -qprime_prmq3/qprime**2
    nprime3_prmq1 = qprime3*uprime_prmq1
    nprime3_prmq2 = qprime3*uprime_prmq2
    nprime3_prmq3 = qprime3*uprime_prmq3 + qprime3_prmq3*uprime
    nprime2_prmq1 = qprime2*uprime_prmq1
    nprime2_prmq2 = qprime2*uprime_prmq2 + qprime2_prmq2*uprime
    nprime2_prmq3 = qprime2*uprime_prmq3
    nprime1_prmq1 = qprime1*uprime_prmq1 + qprime1_prmq1*uprime
    nprime1_prmq2 = qprime1*uprime_prmq2
    nprime1_prmq3 = qprime1*uprime_prmq3
    pprimedotnprime_prmq1 = nprime1_prmq1*pprime1 + nprime2_prmq1*pprime2 + nprime3_prmq1*pprime3
    pprimedotnprime_prmq2 = nprime1_prmq2*pprime1 + nprime2_prmq2*pprime2 + nprime3_prmq2*pprime3
    pprimedotnprime_prmq3 = nprime1_prmq3*pprime1 + nprime2_prmq3*pprime2 + nprime3_prmq3*pprime3
    pprimedotnprime_prmp1 = nprime1*pprime1_prmp1
    pprimedotnprime_prmp2 = nprime2*pprime2_prmp2
    pprimedotnprime_prmp3 = nprime3*pprime3_prmp3
    nprimedotpprimesq_prmq1 = 2*pprimedotnprime*pprimedotnprime_prmq1
    nprimedotpprimesq_prmq2 = 2*pprimedotnprime*pprimedotnprime_prmq2
    nprimedotpprimesq_prmq3 = 2*pprimedotnprime*pprimedotnprime_prmq3
    nprimedotpprimesq_prmp1 = 2*pprimedotnprime*pprimedotnprime_prmp1
    nprimedotpprimesq_prmp2 = 2*pprimedotnprime*pprimedotnprime_prmp2
    nprimedotpprimesq_prmp3 = 2*pprimedotnprime*pprimedotnprime_prmp3
    pprimesq_prmp1 = 2*pprime1*pprime1_prmp1
    pprimesq_prmp2 = 2*pprime2*pprime2_prmp2
    pprimesq_prmp3 = 2*pprime3*pprime3_prmp3
    B_prmq1 = uprime*uprime_prmq1*(8 - 12*eta) + 2*uprime_prmq1
    B_prmq2 = uprime*uprime_prmq2*(8 - 12*eta) + 2*uprime_prmq2
    B_prmq3 = uprime*uprime_prmq3*(8 - 12*eta) + 2*uprime_prmq3
    Binv_prmq1 = -B_prmq1/B**2
    Binv_prmq2 = -B_prmq2/B**2
    Binv_prmq3 = -B_prmq3/B**2
    A_prmq1 = 6*eta*uprime**2*uprime_prmq1 - 2*uprime_prmq1
    A_prmq2 = 6*eta*uprime**2*uprime_prmq2 - 2*uprime_prmq2
    A_prmq3 = 6*eta*uprime**2*uprime_prmq3 - 2*uprime_prmq3
    Heff_prmq1 = np.sqrt(A*(nprimedotpprimesq*(Binv - 1) + pprimesq + 1))*(A*(Binv_prmq1*nprimedotpprimesq + nprimedotpprimesq_prmq1*(Binv - 1))/2 + A_prmq1*(nprimedotpprimesq*(Binv - 1) + pprimesq + 1)/2)/(A*(nprimedotpprimesq*(Binv - 1) + pprimesq + 1))
    Heff_prmq2 = np.sqrt(A*(nprimedotpprimesq*(Binv - 1) + pprimesq + 1))*(A*(Binv_prmq2*nprimedotpprimesq + nprimedotpprimesq_prmq2*(Binv - 1))/2 + A_prmq2*(nprimedotpprimesq*(Binv - 1) + pprimesq + 1)/2)/(A*(nprimedotpprimesq*(Binv - 1) + pprimesq + 1))
    Heff_prmq3 = np.sqrt(A*(nprimedotpprimesq*(Binv - 1) + pprimesq + 1))*(A*(Binv_prmq3*nprimedotpprimesq + nprimedotpprimesq_prmq3*(Binv - 1))/2 + A_prmq3*(nprimedotpprimesq*(Binv - 1) + pprimesq + 1)/2)/(A*(nprimedotpprimesq*(Binv - 1) + pprimesq + 1))
    Heff_prmp1 = np.sqrt(A*(nprimedotpprimesq*(Binv - 1) + pprimesq + 1))*(nprimedotpprimesq_prmp1*(Binv - 1) + pprimesq_prmp1)/(2*(nprimedotpprimesq*(Binv - 1) + pprimesq + 1))
    Heff_prmp2 = np.sqrt(A*(nprimedotpprimesq*(Binv - 1) + pprimesq + 1))*(nprimedotpprimesq_prmp2*(Binv - 1) + pprimesq_prmp2)/(2*(nprimedotpprimesq*(Binv - 1) + pprimesq + 1))
    Heff_prmp3 = np.sqrt(A*(nprimedotpprimesq*(Binv - 1) + pprimesq + 1))*(nprimedotpprimesq_prmp3*(Binv - 1) + pprimesq_prmp3)/(2*(nprimedotpprimesq*(Binv - 1) + pprimesq + 1))
    Hreal_prmq1 = Heff_prmq1/np.sqrt(2*eta*(Heff - 1) + 1)
    Hreal_prmq2 = Heff_prmq2/np.sqrt(2*eta*(Heff - 1) + 1)
    Hreal_prmq3 = Heff_prmq3/np.sqrt(2*eta*(Heff - 1) + 1)
    Hreal_prmp1 = Heff_prmp1/np.sqrt(2*eta*(Heff - 1) + 1)
    Hreal_prmp2 = Heff_prmp2/np.sqrt(2*eta*(Heff - 1) + 1)
    Hreal_prmp3 = Heff_prmp3/np.sqrt(2*eta*(Heff - 1) + 1)
    return np.array([Hreal_prmq1, Hreal_prmq2, Hreal_prmq3, Hreal_prmp1, Hreal_prmp2, Hreal_prmp3])
