from __future__ import division
import numpy as np
def compute_d2Hdpphidr(m1, m2, eta, r, theta, phi, pr, ptheta, pphi, S1r, S1theta, S1phi, S2r, S2theta, S2phi, KK, k0, k1, dSO, dSS, tortoise, EMgamma):
    M = m1+m2
    mu = m1*m2/M
    eta = mu/M
    u = 1/r
    sigmastar3 = m2/m1*S1phi+m1/m2*S2phi
    sigmastar2 = m2/m1*S1theta+m1/m2*S2theta
    sigmastar1 = m2/m1*S1r+m1/m2*S2r
    sigma3 = S1phi+S2phi##Sid:Snp.pinsshouldbeinpolardirections
    sigma2 = S1theta+S2theta
    sigma1 = S1r+S2r
    Skerr3 = sigma3##Sid:Snp.pinsshouldbeinpolardirections
    Skerr2 = sigma2
    Skerr1 = sigma1
    Skerrmag = np.sqrt(Skerr1*Skerr1+Skerr2*Skerr2+Skerr3*Skerr3)
    Skerrhat3 = Skerr3/Skerrmag
    Skerrhat2 = Skerr2/Skerrmag
    Skerrhat1 = Skerr1/Skerrmag
    a = Skerrmag
    n3 = 0
    n2 = 0
    n1 = 1
    e33 = Skerrhat3##Sid:insphericalpolar,nisjust(1,0,0)
    e32 = Skerrhat2
    e31 = Skerrhat1
    xi3 = e31*n2-e32*n1
    xi2 = e33*n1-e31*n3
    xi1 = e32*n3-e33*n2
    v3 = n1*xi2-n2*xi1##Sid:Testingoutatypohere
    v2 = n3*xi1-n1*xi3
    v1 = n2*xi3-n3*xi2
    costhetaBL = e31*n1+e32*n2+e33*n3
    sin2thetaBL = 1-costhetaBL*costhetaBL
    xisq = sin2thetaBL
    w2 = a*a+r*r
    Sigma = r*r+a*a*costhetaBL*costhetaBL
    sintheta = np.sin(theta)##Sid:costhetaBLsubstitution
    Dinv = 1+np.log(1+6*eta*u*u+2*(26-3*eta)*eta*u*u*u)
    omegatilde = 2*a*r
    K = 1.712-1.803949138004582*eta-39.77229225266885*eta*eta+103.16588921239249*eta*eta*eta
    etaKminus1 = eta*K-1
    Delta0 = K*(eta*K-2)
    Delta1 = -2*etaKminus1*(K+Delta0)
    Delta2 = np.true_divide(1,2)*Delta1*(Delta1-4*etaKminus1)-a*a*etaKminus1*etaKminus1*Delta0
    Delta3 = -np.true_divide(1,3)*Delta1*Delta1*Delta1+etaKminus1*Delta1*Delta1+Delta2*Delta1-2*etaKminus1*(Delta2-etaKminus1)-a*a*etaKminus1*etaKminus1*Delta1
    Delta4 = np.true_divide(1,12)*(6*a*a*(Delta1*Delta1-2*Delta2)*etaKminus1*etaKminus1+3*Delta1*Delta1*Delta1*Delta1-8*etaKminus1*Delta1*Delta1*Delta1-12*Delta2*Delta1*Delta1+12*(2*etaKminus1*Delta2+Delta3)*Delta1+12*(np.true_divide(94,3)-np.true_divide(41,32)*np.pi*np.pi)*etaKminus1*etaKminus1+6*(Delta2*Delta2-4*Delta3*etaKminus1))
    Delta5 = etaKminus1*etaKminus1*((np.true_divide(-4237,60)+np.true_divide(128,5)*EMgamma+np.true_divide(2275,512)*np.pi*np.pi-np.true_divide(1,3)*a*a*(Delta1*Delta1*Delta1-3*Delta1*Delta2+3*Delta3)-(Delta1*Delta1*Delta1*Delta1*Delta1-5*Delta1*Delta1*Delta1*Delta2+5*Delta1*Delta2*Delta2+5*Delta1*Delta1*Delta3-5*Delta2*Delta3-5*Delta1*Delta4)/(5*etaKminus1*etaKminus1)+(Delta1*Delta1*Delta1*Delta1-4*Delta1*Delta1*Delta2+2*Delta2*Delta2+4*Delta1*Delta3-4*Delta4)/(2*etaKminus1)+np.true_divide(256,5)*np.log(2)))
    Delta5l = etaKminus1*etaKminus1*np.true_divide(64,5)
    logarg = u*(Delta1+u*(Delta2+u*(Delta3+u*(Delta4+u*(Delta5+Delta5l*np.log(u))))))
    Deltaucalib = 1+eta*(Delta0+np.log(1+logarg))
    Deltaucalibprime = -eta*u*u*(Delta1+u*(2*Delta2+u*(3*Delta3+u*(4*Delta4+u*(5*(Delta5+Delta5l*np.log(u)))))))/(1+logarg)
    Deltaubar = a*a*u*u+(2*u+1/etaKminus1)/etaKminus1
    Deltaubarprime = -2*a*a*u*u*u-2*u*u/(etaKminus1)
    Deltau = Deltaubar*Deltaucalib
    Deltauprime = Deltaubarprime*Deltaucalib+Deltaubar*Deltaucalibprime
    Deltatprime = 2*r*Deltau+r*r*Deltauprime
    Deltat = r*r*Deltau
    Deltar = Deltat*Dinv
    Lambt = w2*w2-a*a*Deltat*sin2thetaBL
    csi = np.sqrt(Deltar*Deltat)/w2##Sid:sin2thetaBLsubstitution
    csi1 = 1+(1-abs(1-tortoise))*(csi-1)
    csi2 = 1+(np.true_divide(1,2)-np.true_divide(1,2)*np.sign(np.true_divide(3,2)-tortoise))*(csi-1)
    prT = csi2*(pr*n1+ptheta*n2/r+pphi*n3/r/sintheta)
    phat3 = pphi/r/sintheta+prT*(1-1/csi1)*n3##Sid:Rewritewithsphericalmomenta
    phat2 = ptheta/r+prT*(1-1/csi1)*n2
    phat1 = pr+prT*(1-1/csi1)*n1
    pdotxir = (phat1*xi1+phat2*xi2+phat3*xi3)*r##Sid:Rewritewithsphericalmomenta
    pdotn = phat1*n1+phat2*n2+phat3*n3
    pdotvr = (phat1*v1+phat2*v2+phat3*v3)*r
    Qcoeff2 = 1/(Sigma*sin2thetaBL)
    Qcoeff1 = Sigma/(Lambt*sin2thetaBL)##Sid:sin2thetaBLsubstitution
    DrSipn2 = Deltar*pdotn*pdotn/Sigma##Sid:sin2thetaBLsubstitution
    Q = 1+DrSipn2+Qcoeff1*pdotxir*pdotxir+Qcoeff2*pdotvr*pdotvr
    Qminus1 = Q-1
    Jtilde = np.sqrt(Deltar)
    exp2mu = Sigma
    expmu = np.sqrt(exp2mu)
    Brtilde = (np.sqrt(Deltar)*Deltatprime-2*Deltat)/(2*np.sqrt(Deltar*Deltat))
    Btilde = np.sqrt(Deltat)
    exp2nu = Deltat*Sigma/Lambt
    expnu = np.sqrt(exp2nu)
    omega = omegatilde/Lambt
    omegatildeprime = 2*a
    Lambtprime = 4*(a*a+r*r)*r-2*a*a*Deltatprime*sin2thetaBL
    mucostheta = a*a*costhetaBL/Sigma##Sid:sin2thetaBLsubstitution
    nucostheta = a*a*w2*costhetaBL*(w2-Deltat)/(Lambt*Sigma)##Sid:costhetaBLsubstitution
    omegacostheta = -2*a*a*costhetaBL*Deltat*omegatilde/(Lambt*Lambt)##Sid:costhetaBLsubstitution
    mur = r/Sigma-1/np.sqrt(Deltar)##Sid:costhetaBLsubstitution
    nur = r/Sigma+w2*(w2*Deltatprime-4*r*Deltat)/(2*Lambt*Deltat)
    omegar = (Lambt*omegatildeprime-Lambtprime*omegatilde)/(Lambt*Lambt)
    dSO = -74.71-156.*eta+627.5*eta*eta
    sigmacoeffTerm3 = eta*dSO*u*u*u
    sigmacoeffTerm2 = eta/(144*r*r)*(-896+r*(-436*Qminus1-96*DrSipn2+r*(-45*Qminus1*Qminus1+36*Qminus1*DrSipn2))+eta*(-336+r*(204*Qminus1-882*DrSipn2+r*(810*DrSipn2*DrSipn2-234*Qminus1*DrSipn2))))
    sigmacoeffTerm1 = eta/12*(-8*u+3*Qminus1-36*DrSipn2)
    sigmacoeff = sigmacoeffTerm1+sigmacoeffTerm2+sigmacoeffTerm3##Sid:Again,multiplybyuinstead
    sigmastarcoeffTerm2 = eta/(72*r*r)*(706+r*(-206*Qminus1+282*DrSipn2+r*Qminus1*(96*DrSipn2-23*Qminus1))+eta*(-54+r*(120*Qminus1-324*DrSipn2+r*(360*DrSipn2*DrSipn2+Qminus1*(-126*DrSipn2-3*Qminus1)))))
    sigmastarcoeffTerm1 = eta/12*(14*u+4*Qminus1-30*DrSipn2)
    sigmastarcoeff = sigmastarcoeffTerm1+sigmastarcoeffTerm2##Sid:Multiplybyuoncemore
    Deltasigmastar3 = sigmastar3*sigmastarcoeff+sigma3*sigmacoeff
    Deltasigmastar2 = sigmastar2*sigmastarcoeff+sigma2*sigmacoeff
    Deltasigmastar1 = sigmastar1*sigmastarcoeff+sigma1*sigmacoeff
    Sstar3 = sigmastar3+Deltasigmastar3
    Sstar2 = sigmastar2+Deltasigmastar2
    Sstar1 = sigmastar1+Deltasigmastar1
    S3 = Sstar3
    S2 = Sstar2
    S1 = Sstar1
    Sstardotn = Sstar1*n1+Sstar2*n2+Sstar3*n3
    SdotSkerrhat = S1*Skerrhat1+S2*Skerrhat2+S3*Skerrhat3
    Sdotn = S1*n1+S2*n2+S3*n3
    Sdotv = S1*v1+S2*v2+S3*v3
    Sdotxi = S1*xi1+S2*xi2+S3*xi3
    HdsumTerm2 = 3*Sstardotn*Sstardotn
    HdsumTerm1 = Sstar1*Sstar1+Sstar2*Sstar2+Sstar3*Sstar3
    Hdsum = HdsumTerm1-HdsumTerm2
    Hdcoeff = np.true_divide(1,2)*(u*u*u)
    Q4 = 2*prT*prT*prT*prT*u*u*(4-3*eta)*eta##Sid:Whydividebyrwhenyoucanmultiplybyu?
    gammappsum = Deltar/Sigma*pdotn*pdotn+1/Sigma*pdotvr*pdotvr/sin2thetaBL+Sigma/Lambt/sin2thetaBL*pdotxir*pdotxir
    Hnsradicand = 1+gammappsum+Q4##Sid:sin2thetaBLsubstitution
    alpha = np.sqrt(Deltat*Sigma/Lambt)
    betapsum = omegatilde*pdotxir/Lambt
    HssTerm3 = expmu*expnu*pdotxir*(Jtilde*pdotn*Sdotxi*Btilde-expmu*expnu*pdotxir*Sdotn)+(pdotvr*(Sdotn*pdotvr-Jtilde*pdotn*Sdotv)-exp2mu*(np.sqrt(Q)+Q)*Sdotn*xisq)*Btilde*Btilde##Sid:Changedtopdotxirtoeliminatepphi
    HssTerm3coeff = omegacostheta/(2*exp2mu*expmu*expnu*Btilde*(Q+np.sqrt(Q)))
    HssTerm2 = expmu*pdotxir*(expmu*exp2nu*pdotxir*Sdotv-expnu*pdotvr*Sdotxi*Btilde)+xisq*Btilde*Btilde*(exp2mu*(np.sqrt(Q)+Q)*Sdotv+Jtilde*pdotn*(pdotvr*Sdotn-Jtilde*pdotn*Sdotv))
    HssTerm2coeff = Jtilde*omegar/(2*exp2mu*expmu*expnu*Btilde*(Q+np.sqrt(Q))*xisq)
    HssTerm1 = omega*SdotSkerrhat
    Hss = HssTerm1+HssTerm2coeff*HssTerm2+HssTerm3coeff*HssTerm3
    HsoTerm2c = Jtilde*Brtilde*expmu*expnu*pdotxir*(np.sqrt(Q)+1)*Sdotv
    HsoTerm2b = expmu*expnu*pdotxir*(2*np.sqrt(Q)+1)*(Jtilde*nur*Sdotv-nucostheta*Sdotn*xisq)*Btilde
    HsoTerm2a = Sdotxi*Jtilde*(mur*pdotvr*(np.sqrt(Q)+1)-mucostheta*pdotn*xisq-np.sqrt(Q)*(nur*pdotvr+(mucostheta-nucostheta)*pdotn*xisq))*Btilde*Btilde
    HsoTerm2 = HsoTerm2a+HsoTerm2b-HsoTerm2c
    HsoTerm2coeff = expnu/(exp2mu*Btilde*Btilde*(Q+np.sqrt(Q))*xisq)
    HsoTerm1 = exp2nu*(expmu*expnu-Btilde)*pdotxir*SdotSkerrhat/(expmu*Btilde*Btilde*np.sqrt(Q)*xisq)
    Hso = HsoTerm1+HsoTerm2coeff*HsoTerm2
    Hd = Hdcoeff*Hdsum
    Hns = betapsum+alpha*np.sqrt(Hnsradicand)
    Hs = Hso+Hss
    dSS = 8.127-154.2*eta+830.8*eta*eta
    Heff = Hs+Hns-Hd+dSS*eta*u*u*u*u*(S1r*S1r+S1theta*S1theta+S1phi*S1phi+S2r*S2r+S2theta*S2theta+S2phi*S2phi)
    prT_pphi = csi2*n3/(r*sintheta)
    phat3_pphi = n3*prT_pphi*(1-1/csi1)+1/(r*sintheta)
    phat2_pphi = n2*prT_pphi*(1-1/csi1)
    phat1_pphi = n1*prT_pphi*(1-1/csi1)
    pdotxir_pphi = r*(phat1_pphi*xi1+phat2_pphi*xi2+phat3_pphi*xi3)
    pdotn_pphi = n1*phat1_pphi+n2*phat2_pphi+n3*phat3_pphi
    pdotvr_pphi = r*(phat1_pphi*v1+phat2_pphi*v2+phat3_pphi*v3)
    DrSipn2_pphi = 2*Deltar*pdotn*pdotn_pphi/Sigma
    Q_pphi = DrSipn2_pphi+2*Qcoeff1*pdotxir*pdotxir_pphi+2*Qcoeff2*pdotvr*pdotvr_pphi
    Qminus1_pphi = Q_pphi
    sigmacoeffTerm2_pphi = eta*(eta*r*(-882*DrSipn2_pphi+204*Qminus1_pphi+r*(1620*DrSipn2*DrSipn2_pphi-234*DrSipn2*Qminus1_pphi-234*DrSipn2_pphi*Qminus1))+r*(-96*DrSipn2_pphi-436*Qminus1_pphi+r*(36*DrSipn2*Qminus1_pphi+36*DrSipn2_pphi*Qminus1-90*Qminus1*Qminus1_pphi)))/(144*r**2)
    sigmacoeffTerm1_pphi = eta*(-36*DrSipn2_pphi+3*Qminus1_pphi)/12
    sigmacoeff_pphi = sigmacoeffTerm1_pphi+sigmacoeffTerm2_pphi
    sigmastarcoeffTerm2_pphi = eta*(eta*r*(-324*DrSipn2_pphi+120*Qminus1_pphi+r*(720*DrSipn2*DrSipn2_pphi+Qminus1*(-126*DrSipn2_pphi-3*Qminus1_pphi)+Qminus1_pphi*(-126*DrSipn2-3*Qminus1)))+r*(282*DrSipn2_pphi+Qminus1*r*(96*DrSipn2_pphi-23*Qminus1_pphi)+Qminus1_pphi*r*(96*DrSipn2-23*Qminus1)-206*Qminus1_pphi))/(72*r**2)
    sigmastarcoeffTerm1_pphi = eta*(-30*DrSipn2_pphi+4*Qminus1_pphi)/12
    sigmastarcoeff_pphi = sigmastarcoeffTerm1_pphi+sigmastarcoeffTerm2_pphi
    Deltasigmastar3_pphi = sigma3*sigmacoeff_pphi+sigmastar3*sigmastarcoeff_pphi
    Deltasigmastar2_pphi = sigma2*sigmacoeff_pphi+sigmastar2*sigmastarcoeff_pphi
    Deltasigmastar1_pphi = sigma1*sigmacoeff_pphi+sigmastar1*sigmastarcoeff_pphi
    Sstar3_pphi = Deltasigmastar3_pphi
    Sstar2_pphi = Deltasigmastar2_pphi
    Sstar1_pphi = Deltasigmastar1_pphi
    S3_pphi = Sstar3_pphi
    S2_pphi = Sstar2_pphi
    S1_pphi = Sstar1_pphi
    Sstardotn_pphi = Sstar1_pphi*n1+Sstar2_pphi*n2+Sstar3_pphi*n3
    SdotSkerrhat_pphi = S1_pphi*Skerrhat1+S2_pphi*Skerrhat2+S3_pphi*Skerrhat3
    Sdotn_pphi = S1_pphi*n1+S2_pphi*n2+S3_pphi*n3
    Sdotv_pphi = S1_pphi*v1+S2_pphi*v2+S3_pphi*v3
    Sdotxi_pphi = S1_pphi*xi1+S2_pphi*xi2+S3_pphi*xi3
    HdsumTerm2_pphi = 6*Sstardotn*Sstardotn_pphi
    HdsumTerm1_pphi = 2*Sstar1*Sstar1_pphi+2*Sstar2*Sstar2_pphi+2*Sstar3*Sstar3_pphi
    Hdsum_pphi = HdsumTerm1_pphi-HdsumTerm2_pphi
    Q4_pphi = 8*eta*prT**3*prT_pphi*u**2*(-3*eta+4)
    gammappsum_pphi = 2*Deltar*pdotn*pdotn_pphi/Sigma+2*pdotvr*pdotvr_pphi/(Sigma*sin2thetaBL)+2*Sigma*pdotxir*pdotxir_pphi/(Lambt*sin2thetaBL)
    Hnsradicand_pphi = Q4_pphi+gammappsum_pphi
    betapsum_pphi = omegatilde*pdotxir_pphi/Lambt
    HssTerm3_pphi = Btilde**2*(Sdotn*exp2mu*xisq*(-Q_pphi-Q_pphi/(2*np.sqrt(Q)))+Sdotn_pphi*exp2mu*xisq*(-np.sqrt(Q)-Q)+pdotvr*(-Jtilde*Sdotv*pdotn_pphi-Jtilde*Sdotv_pphi*pdotn+Sdotn*pdotvr_pphi+Sdotn_pphi*pdotvr)+pdotvr_pphi*(-Jtilde*Sdotv*pdotn+Sdotn*pdotvr))+expmu*expnu*pdotxir*(Btilde*Jtilde*Sdotxi*pdotn_pphi+Btilde*Jtilde*Sdotxi_pphi*pdotn-Sdotn*expmu*expnu*pdotxir_pphi-Sdotn_pphi*expmu*expnu*pdotxir)+expmu*expnu*pdotxir_pphi*(Btilde*Jtilde*Sdotxi*pdotn-Sdotn*expmu*expnu*pdotxir)
    HssTerm3coeff_pphi = omegacostheta*(-Q_pphi-Q_pphi/(2*np.sqrt(Q)))/(2*Btilde*exp2mu*expmu*expnu*(np.sqrt(Q)+Q)**2)
    HssTerm2_pphi = Btilde**2*xisq*(Jtilde*pdotn*(-Jtilde*Sdotv*pdotn_pphi-Jtilde*Sdotv_pphi*pdotn+Sdotn*pdotvr_pphi+Sdotn_pphi*pdotvr)+Jtilde*pdotn_pphi*(-Jtilde*Sdotv*pdotn+Sdotn*pdotvr)+Sdotv*exp2mu*(Q_pphi+Q_pphi/(2*np.sqrt(Q)))+Sdotv_pphi*exp2mu*(np.sqrt(Q)+Q))+expmu*pdotxir*(-Btilde*Sdotxi*expnu*pdotvr_pphi-Btilde*Sdotxi_pphi*expnu*pdotvr+Sdotv*exp2nu*expmu*pdotxir_pphi+Sdotv_pphi*exp2nu*expmu*pdotxir)+expmu*pdotxir_pphi*(-Btilde*Sdotxi*expnu*pdotvr+Sdotv*exp2nu*expmu*pdotxir)
    HssTerm2coeff_pphi = Jtilde*omegar*(-Q_pphi-Q_pphi/(2*np.sqrt(Q)))/(2*Btilde*exp2mu*expmu*expnu*xisq*(np.sqrt(Q)+Q)**2)
    HssTerm1_pphi = SdotSkerrhat_pphi*omega
    Hss_pphi = HssTerm1_pphi+HssTerm2*HssTerm2coeff_pphi+HssTerm2coeff*HssTerm2_pphi+HssTerm3*HssTerm3coeff_pphi+HssTerm3coeff*HssTerm3_pphi
    HsoTerm2c_pphi = Brtilde*Jtilde*Sdotv*expmu*expnu*pdotxir_pphi*(np.sqrt(Q)+1)+Brtilde*Jtilde*Sdotv_pphi*expmu*expnu*pdotxir*(np.sqrt(Q)+1)+Brtilde*Jtilde*Q_pphi*Sdotv*expmu*expnu*pdotxir/(2*np.sqrt(Q))
    HsoTerm2b_pphi = Btilde*expmu*expnu*pdotxir*(2*np.sqrt(Q)+1)*(Jtilde*Sdotv_pphi*nur-Sdotn_pphi*nucostheta*xisq)+Btilde*expmu*expnu*pdotxir_pphi*(2*np.sqrt(Q)+1)*(Jtilde*Sdotv*nur-Sdotn*nucostheta*xisq)+Btilde*Q_pphi*expmu*expnu*pdotxir*(Jtilde*Sdotv*nur-Sdotn*nucostheta*xisq)/np.sqrt(Q)
    HsoTerm2a_pphi = Btilde**2*Jtilde*Sdotxi*(-np.sqrt(Q)*(nur*pdotvr_pphi+pdotn_pphi*xisq*(mucostheta-nucostheta))-mucostheta*pdotn_pphi*xisq+mur*pdotvr_pphi*(np.sqrt(Q)+1)+Q_pphi*mur*pdotvr/(2*np.sqrt(Q))+Q_pphi*(-nur*pdotvr-pdotn*xisq*(mucostheta-nucostheta))/(2*np.sqrt(Q)))+Btilde**2*Jtilde*Sdotxi_pphi*(np.sqrt(Q)*(-nur*pdotvr-pdotn*xisq*(mucostheta-nucostheta))-mucostheta*pdotn*xisq+mur*pdotvr*(np.sqrt(Q)+1))
    HsoTerm2_pphi = HsoTerm2a_pphi+HsoTerm2b_pphi-HsoTerm2c_pphi
    HsoTerm2coeff_pphi = expnu*(-Q_pphi-Q_pphi/(2*np.sqrt(Q)))/(Btilde**2*exp2mu*xisq*(np.sqrt(Q)+Q)**2)
    HsoTerm1_pphi = SdotSkerrhat*exp2nu*pdotxir_pphi*(-Btilde+expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq)+SdotSkerrhat_pphi*exp2nu*pdotxir*(-Btilde+expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq)-Q_pphi*SdotSkerrhat*exp2nu*pdotxir*(-Btilde+expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq)
    Hso_pphi = HsoTerm1_pphi+HsoTerm2*HsoTerm2coeff_pphi+HsoTerm2coeff*HsoTerm2_pphi
    Hd_pphi = Hdcoeff*Hdsum_pphi
    Hns_pphi = betapsum_pphi+Hnsradicand_pphi*alpha/(2*np.sqrt(Hnsradicand))
    Hs_pphi = Hso_pphi+Hss_pphi
    Heff_pphi = -Hd_pphi+Hns_pphi+Hs_pphi
    uprm_r = -1/r**2
    w2prm_r = 2*r
    Sigmaprm_r = 2*r
    Dinvprm_r = (3*eta*u**2*uprm_r*(-6*eta + 52) + 12*eta*u*uprm_r)/(eta*u**3*(-6*eta + 52) + 6*eta*u**2 + 1)
    omegatildeprm_r = 2*a
    logargprm_r = u*(u*(u*(u*(Delta5l*uprm_r + uprm_r*(Delta5 + Delta5l*np.log(u))) + uprm_r*(Delta4 + u*(Delta5 + Delta5l*np.log(u)))) + uprm_r*(Delta3 + u*(Delta4 + u*(Delta5 + Delta5l*np.log(u))))) + uprm_r*(Delta2 + u*(Delta3 + u*(Delta4 + u*(Delta5 + Delta5l*np.log(u)))))) + uprm_r*(Delta1 + u*(Delta2 + u*(Delta3 + u*(Delta4 + u*(Delta5 + Delta5l*np.log(u))))))
    Deltaucalibprm_r = eta*logargprm_r/(logarg + 1)
    Deltaucalibprimeprm_r = eta*logargprm_r*u**2*(Delta1 + u*(2*Delta2 + u*(3*Delta3 + u*(4*Delta4 + u*(5*Delta5 + 5*Delta5l*np.log(u))))))/(logarg + 1)**2 - eta*u**2*(u*(u*(u*(5*Delta5l*uprm_r + uprm_r*(5*Delta5 + 5*Delta5l*np.log(u))) + uprm_r*(4*Delta4 + u*(5*Delta5 + 5*Delta5l*np.log(u)))) + uprm_r*(3*Delta3 + u*(4*Delta4 + u*(5*Delta5 + 5*Delta5l*np.log(u))))) + uprm_r*(2*Delta2 + u*(3*Delta3 + u*(4*Delta4 + u*(5*Delta5 + 5*Delta5l*np.log(u))))))/(logarg + 1) - 2*eta*u*uprm_r*(Delta1 + u*(2*Delta2 + u*(3*Delta3 + u*(4*Delta4 + u*(5*Delta5 + 5*Delta5l*np.log(u))))))/(logarg + 1)
    Deltaubarprm_r = 2*a**2*u*uprm_r + 2*uprm_r/etaKminus1
    Deltaubarprimeprm_r = -6*a**2*u**2*uprm_r - 4*u*uprm_r/etaKminus1
    Deltauprm_r = Deltaubar*Deltaucalibprm_r + Deltaubarprm_r*Deltaucalib
    Deltauprimeprm_r = Deltaubar*Deltaucalibprimeprm_r + Deltaubarprime*Deltaucalibprm_r + Deltaubarprimeprm_r*Deltaucalib + Deltaubarprm_r*Deltaucalibprime
    Deltatprimeprm_r = 2*Deltau + 2*Deltauprime*r + Deltauprimeprm_r*r**2 + 2*Deltauprm_r*r
    Deltatprm_r = 2*Deltau*r + Deltauprm_r*r**2
    Deltarprm_r = Deltat*Dinvprm_r + Deltatprm_r*Dinv
    Lambtprm_r = -Deltatprm_r*a**2*sin2thetaBL + 2*w2*w2prm_r
    csiprm_r = -w2prm_r*np.sqrt(Deltar*Deltat)/w2**2 + np.sqrt(Deltar*Deltat)*(Deltar*Deltatprm_r/2 + Deltarprm_r*Deltat/2)/(Deltar*Deltat*w2)
    csi1prm_r = csiprm_r*(-abs(-tortoise + 1) + 1)
    csi2prm_r = csiprm_r*(-np.sign(-tortoise + 3/2)/2 + 1/2)
    prTprm_r = csi2*(-n2*ptheta/r**2 - n3*pphi/(r**2*sintheta)) + csi2prm_r*(n1*pr + n2*ptheta/r + n3*pphi/(r*sintheta))
    phat3prm_r = n3*prTprm_r*(1 - 1/csi1) - pphi/(r**2*sintheta) + csi1prm_r*n3*prT/csi1**2
    phat2prm_r = n2*prTprm_r*(1 - 1/csi1) - ptheta/r**2 + csi1prm_r*n2*prT/csi1**2
    phat1prm_r = n1*prTprm_r*(1 - 1/csi1) + csi1prm_r*n1*prT/csi1**2
    pdotxirprm_r = phat1*xi1 + phat2*xi2 + phat3*xi3 + r*(phat1prm_r*xi1 + phat2prm_r*xi2 + phat3prm_r*xi3)
    pdotnprm_r = n1*phat1prm_r + n2*phat2prm_r + n3*phat3prm_r
    pdotvrprm_r = phat1*v1 + phat2*v2 + phat3*v3 + r*(phat1prm_r*v1 + phat2prm_r*v2 + phat3prm_r*v3)
    Qcoeff2prm_r = -Sigmaprm_r/(Sigma**2*sin2thetaBL)
    Qcoeff1prm_r = Sigmaprm_r/(Lambt*sin2thetaBL) - Lambtprm_r*Sigma/(Lambt**2*sin2thetaBL)
    DrSipn2prm_r = 2*Deltar*pdotn*pdotnprm_r/Sigma - Deltar*Sigmaprm_r*pdotn**2/Sigma**2 + Deltarprm_r*pdotn**2/Sigma
    Qprm_r = DrSipn2prm_r + 2*Qcoeff1*pdotxir*pdotxirprm_r + Qcoeff1prm_r*pdotxir**2 + 2*Qcoeff2*pdotvr*pdotvrprm_r + Qcoeff2prm_r*pdotvr**2
    Qminus1prm_r = Qprm_r
    Jtildeprm_r = Deltarprm_r/(2*np.sqrt(Deltar))
    exp2muprm_r = Sigmaprm_r
    expmuprm_r = exp2muprm_r/(2*np.sqrt(exp2mu))
    Brtildeprm_r = (np.sqrt(Deltar)*Deltatprimeprm_r - 2*Deltatprm_r + Deltarprm_r*Deltatprime/(2*np.sqrt(Deltar)))/(2*np.sqrt(Deltar*Deltat)) + (np.sqrt(Deltar)*Deltatprime - 2*Deltat)*(-Deltar*Deltatprm_r/2 - Deltarprm_r*Deltat/2)/(2*Deltar*Deltat*np.sqrt(Deltar*Deltat))
    Btildeprm_r = Deltatprm_r/(2*np.sqrt(Deltat))
    exp2nuprm_r = Deltat*Sigmaprm_r/Lambt - Deltat*Lambtprm_r*Sigma/Lambt**2 + Deltatprm_r*Sigma/Lambt
    expnuprm_r = exp2nuprm_r/(2*np.sqrt(exp2nu))
    omegaprm_r = omegatildeprm_r/Lambt - Lambtprm_r*omegatilde/Lambt**2
    Lambtprimeprm_r = -2*Deltatprimeprm_r*a**2*sin2thetaBL + 4*a**2 + 12*r**2
    mucosthetaprm_r = -Sigmaprm_r*a**2*costhetaBL/Sigma**2
    nucosthetaprm_r = a**2*costhetaBL*w2*(-Deltatprm_r + w2prm_r)/(Lambt*Sigma) + a**2*costhetaBL*w2prm_r*(-Deltat + w2)/(Lambt*Sigma) - Sigmaprm_r*a**2*costhetaBL*w2*(-Deltat + w2)/(Lambt*Sigma**2) - Lambtprm_r*a**2*costhetaBL*w2*(-Deltat + w2)/(Lambt**2*Sigma)
    omegacosthetaprm_r = -2*Deltat*a**2*costhetaBL*omegatildeprm_r/Lambt**2 + 4*Deltat*Lambtprm_r*a**2*costhetaBL*omegatilde/Lambt**3 - 2*Deltatprm_r*a**2*costhetaBL*omegatilde/Lambt**2
    murprm_r = 1/Sigma - Sigmaprm_r*r/Sigma**2 + Deltarprm_r/(2*Deltar**(3/2))
    nurprm_r = 1/Sigma - Sigmaprm_r*r/Sigma**2 + w2*(-4*Deltat + Deltatprime*w2prm_r + Deltatprimeprm_r*w2 - 4*Deltatprm_r*r)/(2*Deltat*Lambt) + w2prm_r*(-4*Deltat*r + Deltatprime*w2)/(2*Deltat*Lambt) - Lambtprm_r*w2*(-4*Deltat*r + Deltatprime*w2)/(2*Deltat*Lambt**2) - Deltatprm_r*w2*(-4*Deltat*r + Deltatprime*w2)/(2*Deltat**2*Lambt)
    omegarprm_r = (-Lambtprime*omegatildeprm_r - Lambtprimeprm_r*omegatilde + Lambtprm_r*omegatildeprime)/Lambt**2 + Lambtprm_r*(-2*Lambt*omegatildeprime + 2*Lambtprime*omegatilde)/Lambt**3
    sigmacoeffTerm3prm_r = 3*dSO*eta*u**2*uprm_r
    sigmacoeffTerm2prm_r = eta*(-96*DrSipn2 - 436*Qminus1 + eta*(-882*DrSipn2 + 204*Qminus1 + r*(810*DrSipn2**2 - 234*DrSipn2*Qminus1) + r*(810*DrSipn2**2 - 234*DrSipn2*Qminus1 - 882*DrSipn2prm_r + 204*Qminus1prm_r + r*(1620*DrSipn2*DrSipn2prm_r - 234*DrSipn2*Qminus1prm_r - 234*DrSipn2prm_r*Qminus1))) + r*(36*DrSipn2*Qminus1 - 45*Qminus1**2) + r*(36*DrSipn2*Qminus1 - 96*DrSipn2prm_r - 45*Qminus1**2 - 436*Qminus1prm_r + r*(36*DrSipn2*Qminus1prm_r + 36*DrSipn2prm_r*Qminus1 - 90*Qminus1*Qminus1prm_r)))/(144*r**2) - eta*(eta*(r*(-882*DrSipn2 + 204*Qminus1 + r*(810*DrSipn2**2 - 234*DrSipn2*Qminus1)) - 336) + r*(-96*DrSipn2 - 436*Qminus1 + r*(36*DrSipn2*Qminus1 - 45*Qminus1**2)) - 896)/(72*r**3)
    sigmacoeffTerm1prm_r = eta*(-36*DrSipn2prm_r + 3*Qminus1prm_r - 8*uprm_r)/12
    sigmacoeffprm_r = sigmacoeffTerm1prm_r + sigmacoeffTerm2prm_r + sigmacoeffTerm3prm_r
    sigmastarcoeffTerm2prm_r = eta*(282*DrSipn2 + Qminus1*r*(96*DrSipn2 - 23*Qminus1) - 206*Qminus1 + eta*(-324*DrSipn2 + 120*Qminus1 + r*(360*DrSipn2**2 + Qminus1*(-126*DrSipn2 - 3*Qminus1)) + r*(360*DrSipn2**2 - 324*DrSipn2prm_r + Qminus1*(-126*DrSipn2 - 3*Qminus1) + 120*Qminus1prm_r + r*(720*DrSipn2*DrSipn2prm_r + Qminus1*(-126*DrSipn2prm_r - 3*Qminus1prm_r) + Qminus1prm_r*(-126*DrSipn2 - 3*Qminus1)))) + r*(282*DrSipn2prm_r + Qminus1*r*(96*DrSipn2prm_r - 23*Qminus1prm_r) + Qminus1*(96*DrSipn2 - 23*Qminus1) + Qminus1prm_r*r*(96*DrSipn2 - 23*Qminus1) - 206*Qminus1prm_r))/(72*r**2) - eta*(eta*(r*(-324*DrSipn2 + 120*Qminus1 + r*(360*DrSipn2**2 + Qminus1*(-126*DrSipn2 - 3*Qminus1))) - 54) + r*(282*DrSipn2 + Qminus1*r*(96*DrSipn2 - 23*Qminus1) - 206*Qminus1) + 706)/(36*r**3)
    sigmastarcoeffTerm1prm_r = eta*(-30*DrSipn2prm_r + 4*Qminus1prm_r + 14*uprm_r)/12
    sigmastarcoeffprm_r = sigmastarcoeffTerm1prm_r + sigmastarcoeffTerm2prm_r
    Deltasigmastar3prm_r = sigma3*sigmacoeffprm_r + sigmastar3*sigmastarcoeffprm_r
    Deltasigmastar2prm_r = sigma2*sigmacoeffprm_r + sigmastar2*sigmastarcoeffprm_r
    Deltasigmastar1prm_r = sigma1*sigmacoeffprm_r + sigmastar1*sigmastarcoeffprm_r
    Sstar3prm_r = Deltasigmastar3prm_r
    Sstar2prm_r = Deltasigmastar2prm_r
    Sstar1prm_r = Deltasigmastar1prm_r
    S3prm_r = Sstar3prm_r
    S2prm_r = Sstar2prm_r
    S1prm_r = Sstar1prm_r
    Sstardotnprm_r = Sstar1prm_r*n1 + Sstar2prm_r*n2 + Sstar3prm_r*n3
    SdotSkerrhatprm_r = S1prm_r*Skerrhat1 + S2prm_r*Skerrhat2 + S3prm_r*Skerrhat3
    Sdotnprm_r = S1prm_r*n1 + S2prm_r*n2 + S3prm_r*n3
    Sdotvprm_r = S1prm_r*v1 + S2prm_r*v2 + S3prm_r*v3
    Sdotxiprm_r = S1prm_r*xi1 + S2prm_r*xi2 + S3prm_r*xi3
    HdsumTerm2prm_r = 6*Sstardotn*Sstardotnprm_r
    HdsumTerm1prm_r = 2*Sstar1*Sstar1prm_r + 2*Sstar2*Sstar2prm_r + 2*Sstar3*Sstar3prm_r
    Hdsumprm_r = HdsumTerm1prm_r - HdsumTerm2prm_r
    Hdcoeffprm_r = 3*u**2*uprm_r/2
    Q4prm_r = 4*eta*prT**4*u*uprm_r*(-3*eta + 4) + 8*eta*prT**3*prTprm_r*u**2*(-3*eta + 4)
    gammappsumprm_r = 2*Deltar*pdotn*pdotnprm_r/Sigma - Deltar*Sigmaprm_r*pdotn**2/Sigma**2 + Deltarprm_r*pdotn**2/Sigma + 2*pdotvr*pdotvrprm_r/(Sigma*sin2thetaBL) - Sigmaprm_r*pdotvr**2/(Sigma**2*sin2thetaBL) + 2*Sigma*pdotxir*pdotxirprm_r/(Lambt*sin2thetaBL) + Sigmaprm_r*pdotxir**2/(Lambt*sin2thetaBL) - Lambtprm_r*Sigma*pdotxir**2/(Lambt**2*sin2thetaBL)
    Hnsradicandprm_r = Q4prm_r + gammappsumprm_r
    alphaprm_r = Lambt*np.sqrt(Deltat*Sigma/Lambt)*(Deltat*Sigmaprm_r/(2*Lambt) - Deltat*Lambtprm_r*Sigma/(2*Lambt**2) + Deltatprm_r*Sigma/(2*Lambt))/(Deltat*Sigma)
    betapsumprm_r = omegatilde*pdotxirprm_r/Lambt + omegatildeprm_r*pdotxir/Lambt - Lambtprm_r*omegatilde*pdotxir/Lambt**2
    HssTerm3prm_r = Btilde**2*(Sdotn*exp2mu*xisq*(-Qprm_r - Qprm_r/(2*np.sqrt(Q))) + Sdotn*exp2muprm_r*xisq*(-np.sqrt(Q) - Q) + Sdotnprm_r*exp2mu*xisq*(-np.sqrt(Q) - Q) + pdotvr*(-Jtilde*Sdotv*pdotnprm_r - Jtilde*Sdotvprm_r*pdotn - Jtildeprm_r*Sdotv*pdotn + Sdotn*pdotvrprm_r + Sdotnprm_r*pdotvr) + pdotvrprm_r*(-Jtilde*Sdotv*pdotn + Sdotn*pdotvr)) + Btilde*Btildeprm_r*(-2*Sdotn*exp2mu*xisq*(np.sqrt(Q) + Q) + 2*pdotvr*(-Jtilde*Sdotv*pdotn + Sdotn*pdotvr)) + expmu*expnu*pdotxir*(Btilde*Jtilde*Sdotxi*pdotnprm_r + Btilde*Jtilde*Sdotxiprm_r*pdotn + Btilde*Jtildeprm_r*Sdotxi*pdotn + Btildeprm_r*Jtilde*Sdotxi*pdotn - Sdotn*expmu*expnu*pdotxirprm_r - Sdotn*expmu*expnuprm_r*pdotxir - Sdotn*expmuprm_r*expnu*pdotxir - Sdotnprm_r*expmu*expnu*pdotxir) + expmu*expnu*pdotxirprm_r*(Btilde*Jtilde*Sdotxi*pdotn - Sdotn*expmu*expnu*pdotxir) + expmu*expnuprm_r*pdotxir*(Btilde*Jtilde*Sdotxi*pdotn - Sdotn*expmu*expnu*pdotxir) + expmuprm_r*expnu*pdotxir*(Btilde*Jtilde*Sdotxi*pdotn - Sdotn*expmu*expnu*pdotxir)
    HssTerm3coeffprm_r = omegacostheta*(-Qprm_r - Qprm_r/(2*np.sqrt(Q)))/(2*Btilde*exp2mu*expmu*expnu*(np.sqrt(Q) + Q)**2) + omegacosthetaprm_r/(Btilde*exp2mu*expmu*expnu*(2*np.sqrt(Q) + 2*Q)) - expnuprm_r*omegacostheta/(Btilde*exp2mu*expmu*expnu**2*(2*np.sqrt(Q) + 2*Q)) - expmuprm_r*omegacostheta/(Btilde*exp2mu*expmu**2*expnu*(2*np.sqrt(Q) + 2*Q)) - exp2muprm_r*omegacostheta/(Btilde*exp2mu**2*expmu*expnu*(2*np.sqrt(Q) + 2*Q)) - Btildeprm_r*omegacostheta/(Btilde**2*exp2mu*expmu*expnu*(2*np.sqrt(Q) + 2*Q))
    HssTerm2prm_r = Btilde**2*xisq*(Jtilde*pdotn*(-Jtilde*Sdotv*pdotnprm_r - Jtilde*Sdotvprm_r*pdotn - Jtildeprm_r*Sdotv*pdotn + Sdotn*pdotvrprm_r + Sdotnprm_r*pdotvr) + Jtilde*pdotnprm_r*(-Jtilde*Sdotv*pdotn + Sdotn*pdotvr) + Jtildeprm_r*pdotn*(-Jtilde*Sdotv*pdotn + Sdotn*pdotvr) + Sdotv*exp2mu*(Qprm_r + Qprm_r/(2*np.sqrt(Q))) + Sdotv*exp2muprm_r*(np.sqrt(Q) + Q) + Sdotvprm_r*exp2mu*(np.sqrt(Q) + Q)) + Btilde*Btildeprm_r*xisq*(2*Jtilde*pdotn*(-Jtilde*Sdotv*pdotn + Sdotn*pdotvr) + 2*Sdotv*exp2mu*(np.sqrt(Q) + Q)) + expmu*pdotxir*(-Btilde*Sdotxi*expnu*pdotvrprm_r - Btilde*Sdotxi*expnuprm_r*pdotvr - Btilde*Sdotxiprm_r*expnu*pdotvr - Btildeprm_r*Sdotxi*expnu*pdotvr + Sdotv*exp2nu*expmu*pdotxirprm_r + Sdotv*exp2nu*expmuprm_r*pdotxir + Sdotv*exp2nuprm_r*expmu*pdotxir + Sdotvprm_r*exp2nu*expmu*pdotxir) + expmu*pdotxirprm_r*(-Btilde*Sdotxi*expnu*pdotvr + Sdotv*exp2nu*expmu*pdotxir) + expmuprm_r*pdotxir*(-Btilde*Sdotxi*expnu*pdotvr + Sdotv*exp2nu*expmu*pdotxir)
    HssTerm2coeffprm_r = Jtilde*omegar*(-Qprm_r - Qprm_r/(2*np.sqrt(Q)))/(2*Btilde*exp2mu*expmu*expnu*xisq*(np.sqrt(Q) + Q)**2) + Jtilde*omegarprm_r/(Btilde*exp2mu*expmu*expnu*xisq*(2*np.sqrt(Q) + 2*Q)) - Jtilde*expnuprm_r*omegar/(Btilde*exp2mu*expmu*expnu**2*xisq*(2*np.sqrt(Q) + 2*Q)) - Jtilde*expmuprm_r*omegar/(Btilde*exp2mu*expmu**2*expnu*xisq*(2*np.sqrt(Q) + 2*Q)) - Jtilde*exp2muprm_r*omegar/(Btilde*exp2mu**2*expmu*expnu*xisq*(2*np.sqrt(Q) + 2*Q)) + Jtildeprm_r*omegar/(Btilde*exp2mu*expmu*expnu*xisq*(2*np.sqrt(Q) + 2*Q)) - Btildeprm_r*Jtilde*omegar/(Btilde**2*exp2mu*expmu*expnu*xisq*(2*np.sqrt(Q) + 2*Q))
    HssTerm1prm_r = SdotSkerrhat*omegaprm_r + SdotSkerrhatprm_r*omega
    Hssprm_r = HssTerm1prm_r + HssTerm2*HssTerm2coeffprm_r + HssTerm2coeff*HssTerm2prm_r + HssTerm3*HssTerm3coeffprm_r + HssTerm3coeff*HssTerm3prm_r
    HsoTerm2cprm_r = Brtilde*Jtilde*Sdotv*expmu*expnu*pdotxirprm_r*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotv*expmu*expnuprm_r*pdotxir*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotv*expmuprm_r*expnu*pdotxir*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotvprm_r*expmu*expnu*pdotxir*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Qprm_r*Sdotv*expmu*expnu*pdotxir/(2*np.sqrt(Q)) + Brtilde*Jtildeprm_r*Sdotv*expmu*expnu*pdotxir*(np.sqrt(Q) + 1) + Brtildeprm_r*Jtilde*Sdotv*expmu*expnu*pdotxir*(np.sqrt(Q) + 1)
    HsoTerm2bprm_r = Btilde*expmu*expnu*pdotxir*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv*nurprm_r + Jtilde*Sdotvprm_r*nur + Jtildeprm_r*Sdotv*nur - Sdotn*nucosthetaprm_r*xisq - Sdotnprm_r*nucostheta*xisq) + Btilde*expmu*expnu*pdotxirprm_r*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq) + Btilde*expmu*expnuprm_r*pdotxir*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq) + Btilde*expmuprm_r*expnu*pdotxir*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq) + Btilde*Qprm_r*expmu*expnu*pdotxir*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq)/np.sqrt(Q) + Btildeprm_r*expmu*expnu*pdotxir*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq)
    HsoTerm2aprm_r = Btilde**2*Jtilde*Sdotxi*(-np.sqrt(Q)*(nur*pdotvrprm_r + nurprm_r*pdotvr + pdotn*xisq*(mucosthetaprm_r - nucosthetaprm_r) + pdotnprm_r*xisq*(mucostheta - nucostheta)) - mucostheta*pdotnprm_r*xisq - mucosthetaprm_r*pdotn*xisq + mur*pdotvrprm_r*(np.sqrt(Q) + 1) + murprm_r*pdotvr*(np.sqrt(Q) + 1) + Qprm_r*mur*pdotvr/(2*np.sqrt(Q)) + Qprm_r*(-nur*pdotvr - pdotn*xisq*(mucostheta - nucostheta))/(2*np.sqrt(Q))) + Btilde**2*Jtilde*Sdotxiprm_r*(np.sqrt(Q)*(-nur*pdotvr - pdotn*xisq*(mucostheta - nucostheta)) - mucostheta*pdotn*xisq + mur*pdotvr*(np.sqrt(Q) + 1)) + Btilde**2*Jtildeprm_r*Sdotxi*(np.sqrt(Q)*(-nur*pdotvr - pdotn*xisq*(mucostheta - nucostheta)) - mucostheta*pdotn*xisq + mur*pdotvr*(np.sqrt(Q) + 1)) + Btilde*Btildeprm_r*Jtilde*Sdotxi*(2*np.sqrt(Q)*(-nur*pdotvr - pdotn*xisq*(mucostheta - nucostheta)) - 2*mucostheta*pdotn*xisq + 2*mur*pdotvr*(np.sqrt(Q) + 1))
    HsoTerm2prm_r = HsoTerm2aprm_r + HsoTerm2bprm_r - HsoTerm2cprm_r
    HsoTerm2coeffprm_r = expnu*(-Qprm_r - Qprm_r/(2*np.sqrt(Q)))/(Btilde**2*exp2mu*xisq*(np.sqrt(Q) + Q)**2) + expnuprm_r/(Btilde**2*exp2mu*xisq*(np.sqrt(Q) + Q)) - exp2muprm_r*expnu/(Btilde**2*exp2mu**2*xisq*(np.sqrt(Q) + Q)) - 2*Btildeprm_r*expnu/(Btilde**3*exp2mu*xisq*(np.sqrt(Q) + Q))
    HsoTerm1prm_r = SdotSkerrhat*exp2nu*pdotxir*(-Btildeprm_r + expmu*expnuprm_r + expmuprm_r*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) + SdotSkerrhat*exp2nu*pdotxirprm_r*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) - SdotSkerrhat*exp2nu*expmuprm_r*pdotxir*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu**2*xisq) + SdotSkerrhat*exp2nuprm_r*pdotxir*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) + SdotSkerrhatprm_r*exp2nu*pdotxir*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) - Qprm_r*SdotSkerrhat*exp2nu*pdotxir*(-Btilde + expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq) - Btildeprm_r*SdotSkerrhat*exp2nu*pdotxir*(-2*Btilde + 2*expmu*expnu)/(Btilde**3*np.sqrt(Q)*expmu*xisq)
    Hsoprm_r = HsoTerm1prm_r + HsoTerm2*HsoTerm2coeffprm_r + HsoTerm2coeff*HsoTerm2prm_r
    Hdprm_r = Hdcoeff*Hdsumprm_r + Hdcoeffprm_r*Hdsum
    Hnsprm_r = np.sqrt(Hnsradicand)*alphaprm_r + betapsumprm_r + Hnsradicandprm_r*alpha/(2*np.sqrt(Hnsradicand))
    Hsprm_r = Hsoprm_r + Hssprm_r
    Heffprm_r = -Hdprm_r + Hnsprm_r + Hsprm_r + 4*dSS*eta*u**3*uprm_r*(S1phi**2 + S1r**2 + S1theta**2 + S2phi**2 + S2r**2 + S2theta**2)
    prT_pphiprm_r = -csi2*n3/(r**2*sintheta) + csi2prm_r*n3/(r*sintheta)
    phat3_pphiprm_r = n3*prT_pphiprm_r*(1 - 1/csi1) - 1/(r**2*sintheta) + csi1prm_r*n3*prT_pphi/csi1**2
    phat2_pphiprm_r = n2*prT_pphiprm_r*(1 - 1/csi1) + csi1prm_r*n2*prT_pphi/csi1**2
    phat1_pphiprm_r = n1*prT_pphiprm_r*(1 - 1/csi1) + csi1prm_r*n1*prT_pphi/csi1**2
    pdotxir_pphiprm_r = phat1_pphi*xi1 + phat2_pphi*xi2 + phat3_pphi*xi3 + r*(phat1_pphiprm_r*xi1 + phat2_pphiprm_r*xi2 + phat3_pphiprm_r*xi3)
    pdotn_pphiprm_r = n1*phat1_pphiprm_r + n2*phat2_pphiprm_r + n3*phat3_pphiprm_r
    pdotvr_pphiprm_r = phat1_pphi*v1 + phat2_pphi*v2 + phat3_pphi*v3 + r*(phat1_pphiprm_r*v1 + phat2_pphiprm_r*v2 + phat3_pphiprm_r*v3)
    DrSipn2_pphiprm_r = 2*Deltar*pdotn*pdotn_pphiprm_r/Sigma + 2*Deltar*pdotn_pphi*pdotnprm_r/Sigma - 2*Deltar*Sigmaprm_r*pdotn*pdotn_pphi/Sigma**2 + 2*Deltarprm_r*pdotn*pdotn_pphi/Sigma
    Q_pphiprm_r = DrSipn2_pphiprm_r + 2*Qcoeff1*pdotxir*pdotxir_pphiprm_r + 2*Qcoeff1*pdotxir_pphi*pdotxirprm_r + 2*Qcoeff1prm_r*pdotxir*pdotxir_pphi + 2*Qcoeff2*pdotvr*pdotvr_pphiprm_r + 2*Qcoeff2*pdotvr_pphi*pdotvrprm_r + 2*Qcoeff2prm_r*pdotvr*pdotvr_pphi
    Qminus1_pphiprm_r = Q_pphiprm_r
    sigmacoeffTerm2_pphiprm_r = eta*(-96*DrSipn2_pphi - 436*Qminus1_pphi + eta*r*(1620*DrSipn2*DrSipn2_pphi - 234*DrSipn2*Qminus1_pphi - 234*DrSipn2_pphi*Qminus1 - 882*DrSipn2_pphiprm_r + 204*Qminus1_pphiprm_r + r*(1620*DrSipn2*DrSipn2_pphiprm_r - 234*DrSipn2*Qminus1_pphiprm_r + 1620*DrSipn2_pphi*DrSipn2prm_r - 234*DrSipn2_pphi*Qminus1prm_r - 234*DrSipn2_pphiprm_r*Qminus1 - 234*DrSipn2prm_r*Qminus1_pphi)) + eta*(-882*DrSipn2_pphi + 204*Qminus1_pphi + r*(1620*DrSipn2*DrSipn2_pphi - 234*DrSipn2*Qminus1_pphi - 234*DrSipn2_pphi*Qminus1)) + r*(36*DrSipn2*Qminus1_pphi + 36*DrSipn2_pphi*Qminus1 - 90*Qminus1*Qminus1_pphi) + r*(36*DrSipn2*Qminus1_pphi + 36*DrSipn2_pphi*Qminus1 - 96*DrSipn2_pphiprm_r - 90*Qminus1*Qminus1_pphi - 436*Qminus1_pphiprm_r + r*(36*DrSipn2*Qminus1_pphiprm_r + 36*DrSipn2_pphi*Qminus1prm_r + 36*DrSipn2_pphiprm_r*Qminus1 + 36*DrSipn2prm_r*Qminus1_pphi - 90*Qminus1*Qminus1_pphiprm_r - 90*Qminus1_pphi*Qminus1prm_r)))/(144*r**2) - eta*(eta*r*(-882*DrSipn2_pphi + 204*Qminus1_pphi + r*(1620*DrSipn2*DrSipn2_pphi - 234*DrSipn2*Qminus1_pphi - 234*DrSipn2_pphi*Qminus1)) + r*(-96*DrSipn2_pphi - 436*Qminus1_pphi + r*(36*DrSipn2*Qminus1_pphi + 36*DrSipn2_pphi*Qminus1 - 90*Qminus1*Qminus1_pphi)))/(72*r**3)
    sigmacoeffTerm1_pphiprm_r = eta*(-36*DrSipn2_pphiprm_r + 3*Qminus1_pphiprm_r)/12
    sigmacoeff_pphiprm_r = sigmacoeffTerm1_pphiprm_r + sigmacoeffTerm2_pphiprm_r
    sigmastarcoeffTerm2_pphiprm_r = eta*(282*DrSipn2_pphi + Qminus1*r*(96*DrSipn2_pphi - 23*Qminus1_pphi) + Qminus1_pphi*r*(96*DrSipn2 - 23*Qminus1) - 206*Qminus1_pphi + eta*r*(720*DrSipn2*DrSipn2_pphi - 324*DrSipn2_pphiprm_r + Qminus1*(-126*DrSipn2_pphi - 3*Qminus1_pphi) + Qminus1_pphi*(-126*DrSipn2 - 3*Qminus1) + 120*Qminus1_pphiprm_r + r*(720*DrSipn2*DrSipn2_pphiprm_r + 720*DrSipn2_pphi*DrSipn2prm_r + Qminus1*(-126*DrSipn2_pphiprm_r - 3*Qminus1_pphiprm_r) + Qminus1_pphi*(-126*DrSipn2prm_r - 3*Qminus1prm_r) + Qminus1_pphiprm_r*(-126*DrSipn2 - 3*Qminus1) + Qminus1prm_r*(-126*DrSipn2_pphi - 3*Qminus1_pphi))) + eta*(-324*DrSipn2_pphi + 120*Qminus1_pphi + r*(720*DrSipn2*DrSipn2_pphi + Qminus1*(-126*DrSipn2_pphi - 3*Qminus1_pphi) + Qminus1_pphi*(-126*DrSipn2 - 3*Qminus1))) + r*(282*DrSipn2_pphiprm_r + Qminus1*r*(96*DrSipn2_pphiprm_r - 23*Qminus1_pphiprm_r) + Qminus1*(96*DrSipn2_pphi - 23*Qminus1_pphi) + Qminus1_pphi*r*(96*DrSipn2prm_r - 23*Qminus1prm_r) + Qminus1_pphi*(96*DrSipn2 - 23*Qminus1) + Qminus1_pphiprm_r*r*(96*DrSipn2 - 23*Qminus1) - 206*Qminus1_pphiprm_r + Qminus1prm_r*r*(96*DrSipn2_pphi - 23*Qminus1_pphi)))/(72*r**2) - eta*(eta*r*(-324*DrSipn2_pphi + 120*Qminus1_pphi + r*(720*DrSipn2*DrSipn2_pphi + Qminus1*(-126*DrSipn2_pphi - 3*Qminus1_pphi) + Qminus1_pphi*(-126*DrSipn2 - 3*Qminus1))) + r*(282*DrSipn2_pphi + Qminus1*r*(96*DrSipn2_pphi - 23*Qminus1_pphi) + Qminus1_pphi*r*(96*DrSipn2 - 23*Qminus1) - 206*Qminus1_pphi))/(36*r**3)
    sigmastarcoeffTerm1_pphiprm_r = eta*(-30*DrSipn2_pphiprm_r + 4*Qminus1_pphiprm_r)/12
    sigmastarcoeff_pphiprm_r = sigmastarcoeffTerm1_pphiprm_r + sigmastarcoeffTerm2_pphiprm_r
    Deltasigmastar3_pphiprm_r = sigma3*sigmacoeff_pphiprm_r + sigmastar3*sigmastarcoeff_pphiprm_r
    Deltasigmastar2_pphiprm_r = sigma2*sigmacoeff_pphiprm_r + sigmastar2*sigmastarcoeff_pphiprm_r
    Deltasigmastar1_pphiprm_r = sigma1*sigmacoeff_pphiprm_r + sigmastar1*sigmastarcoeff_pphiprm_r
    Sstar3_pphiprm_r = Deltasigmastar3_pphiprm_r
    Sstar2_pphiprm_r = Deltasigmastar2_pphiprm_r
    Sstar1_pphiprm_r = Deltasigmastar1_pphiprm_r
    S3_pphiprm_r = Sstar3_pphiprm_r
    S2_pphiprm_r = Sstar2_pphiprm_r
    S1_pphiprm_r = Sstar1_pphiprm_r
    Sstardotn_pphiprm_r = Sstar1_pphiprm_r*n1 + Sstar2_pphiprm_r*n2 + Sstar3_pphiprm_r*n3
    SdotSkerrhat_pphiprm_r = S1_pphiprm_r*Skerrhat1 + S2_pphiprm_r*Skerrhat2 + S3_pphiprm_r*Skerrhat3
    Sdotn_pphiprm_r = S1_pphiprm_r*n1 + S2_pphiprm_r*n2 + S3_pphiprm_r*n3
    Sdotv_pphiprm_r = S1_pphiprm_r*v1 + S2_pphiprm_r*v2 + S3_pphiprm_r*v3
    Sdotxi_pphiprm_r = S1_pphiprm_r*xi1 + S2_pphiprm_r*xi2 + S3_pphiprm_r*xi3
    HdsumTerm2_pphiprm_r = 6*Sstardotn*Sstardotn_pphiprm_r + 6*Sstardotn_pphi*Sstardotnprm_r
    HdsumTerm1_pphiprm_r = 2*Sstar1*Sstar1_pphiprm_r + 2*Sstar1_pphi*Sstar1prm_r + 2*Sstar2*Sstar2_pphiprm_r + 2*Sstar2_pphi*Sstar2prm_r + 2*Sstar3*Sstar3_pphiprm_r + 2*Sstar3_pphi*Sstar3prm_r
    Hdsum_pphiprm_r = HdsumTerm1_pphiprm_r - HdsumTerm2_pphiprm_r
    Q4_pphiprm_r = 16*eta*prT**3*prT_pphi*u*uprm_r*(-3*eta + 4) + 8*eta*prT**3*prT_pphiprm_r*u**2*(-3*eta + 4) + 24*eta*prT**2*prT_pphi*prTprm_r*u**2*(-3*eta + 4)
    gammappsum_pphiprm_r = 2*Deltar*pdotn*pdotn_pphiprm_r/Sigma + 2*Deltar*pdotn_pphi*pdotnprm_r/Sigma - 2*Deltar*Sigmaprm_r*pdotn*pdotn_pphi/Sigma**2 + 2*Deltarprm_r*pdotn*pdotn_pphi/Sigma + 2*pdotvr*pdotvr_pphiprm_r/(Sigma*sin2thetaBL) + 2*pdotvr_pphi*pdotvrprm_r/(Sigma*sin2thetaBL) - 2*Sigmaprm_r*pdotvr*pdotvr_pphi/(Sigma**2*sin2thetaBL) + 2*Sigma*pdotxir*pdotxir_pphiprm_r/(Lambt*sin2thetaBL) + 2*Sigma*pdotxir_pphi*pdotxirprm_r/(Lambt*sin2thetaBL) + 2*Sigmaprm_r*pdotxir*pdotxir_pphi/(Lambt*sin2thetaBL) - 2*Lambtprm_r*Sigma*pdotxir*pdotxir_pphi/(Lambt**2*sin2thetaBL)
    Hnsradicand_pphiprm_r = Q4_pphiprm_r + gammappsum_pphiprm_r
    betapsum_pphiprm_r = omegatilde*pdotxir_pphiprm_r/Lambt + omegatildeprm_r*pdotxir_pphi/Lambt - Lambtprm_r*omegatilde*pdotxir_pphi/Lambt**2
    HssTerm3_pphiprm_r = Btilde**2*(Sdotn*exp2mu*xisq*(-Q_pphiprm_r - Q_pphiprm_r/(2*np.sqrt(Q)) + Q_pphi*Qprm_r/(4*Q**(3/2))) + Sdotn*exp2muprm_r*xisq*(-Q_pphi - Q_pphi/(2*np.sqrt(Q))) + Sdotn_pphi*exp2mu*xisq*(-Qprm_r - Qprm_r/(2*np.sqrt(Q))) + Sdotn_pphi*exp2muprm_r*xisq*(-np.sqrt(Q) - Q) + Sdotn_pphiprm_r*exp2mu*xisq*(-np.sqrt(Q) - Q) + Sdotnprm_r*exp2mu*xisq*(-Q_pphi - Q_pphi/(2*np.sqrt(Q))) + pdotvr*(-Jtilde*Sdotv*pdotn_pphiprm_r - Jtilde*Sdotv_pphi*pdotnprm_r - Jtilde*Sdotv_pphiprm_r*pdotn - Jtilde*Sdotvprm_r*pdotn_pphi - Jtildeprm_r*Sdotv*pdotn_pphi - Jtildeprm_r*Sdotv_pphi*pdotn + Sdotn*pdotvr_pphiprm_r + Sdotn_pphi*pdotvrprm_r + Sdotn_pphiprm_r*pdotvr + Sdotnprm_r*pdotvr_pphi) + pdotvr_pphi*(-Jtilde*Sdotv*pdotnprm_r - Jtilde*Sdotvprm_r*pdotn - Jtildeprm_r*Sdotv*pdotn + Sdotn*pdotvrprm_r + Sdotnprm_r*pdotvr) + pdotvr_pphiprm_r*(-Jtilde*Sdotv*pdotn + Sdotn*pdotvr) + pdotvrprm_r*(-Jtilde*Sdotv*pdotn_pphi - Jtilde*Sdotv_pphi*pdotn + Sdotn*pdotvr_pphi + Sdotn_pphi*pdotvr)) + Btilde*Btildeprm_r*(2*Sdotn*exp2mu*xisq*(-Q_pphi - Q_pphi/(2*np.sqrt(Q))) + 2*Sdotn_pphi*exp2mu*xisq*(-np.sqrt(Q) - Q) + 2*pdotvr*(-Jtilde*Sdotv*pdotn_pphi - Jtilde*Sdotv_pphi*pdotn + Sdotn*pdotvr_pphi + Sdotn_pphi*pdotvr) + 2*pdotvr_pphi*(-Jtilde*Sdotv*pdotn + Sdotn*pdotvr)) + expmu*expnu*pdotxir*(Btilde*Jtilde*Sdotxi*pdotn_pphiprm_r + Btilde*Jtilde*Sdotxi_pphi*pdotnprm_r + Btilde*Jtilde*Sdotxi_pphiprm_r*pdotn + Btilde*Jtilde*Sdotxiprm_r*pdotn_pphi + Btilde*Jtildeprm_r*Sdotxi*pdotn_pphi + Btilde*Jtildeprm_r*Sdotxi_pphi*pdotn + Btildeprm_r*Jtilde*Sdotxi*pdotn_pphi + Btildeprm_r*Jtilde*Sdotxi_pphi*pdotn - Sdotn*expmu*expnu*pdotxir_pphiprm_r - Sdotn*expmu*expnuprm_r*pdotxir_pphi - Sdotn*expmuprm_r*expnu*pdotxir_pphi - Sdotn_pphi*expmu*expnu*pdotxirprm_r - Sdotn_pphi*expmu*expnuprm_r*pdotxir - Sdotn_pphi*expmuprm_r*expnu*pdotxir - Sdotn_pphiprm_r*expmu*expnu*pdotxir - Sdotnprm_r*expmu*expnu*pdotxir_pphi) + expmu*expnu*pdotxir_pphi*(Btilde*Jtilde*Sdotxi*pdotnprm_r + Btilde*Jtilde*Sdotxiprm_r*pdotn + Btilde*Jtildeprm_r*Sdotxi*pdotn + Btildeprm_r*Jtilde*Sdotxi*pdotn - Sdotn*expmu*expnu*pdotxirprm_r - Sdotn*expmu*expnuprm_r*pdotxir - Sdotn*expmuprm_r*expnu*pdotxir - Sdotnprm_r*expmu*expnu*pdotxir) + expmu*expnu*pdotxir_pphiprm_r*(Btilde*Jtilde*Sdotxi*pdotn - Sdotn*expmu*expnu*pdotxir) + expmu*expnu*pdotxirprm_r*(Btilde*Jtilde*Sdotxi*pdotn_pphi + Btilde*Jtilde*Sdotxi_pphi*pdotn - Sdotn*expmu*expnu*pdotxir_pphi - Sdotn_pphi*expmu*expnu*pdotxir) + expmu*expnuprm_r*pdotxir*(Btilde*Jtilde*Sdotxi*pdotn_pphi + Btilde*Jtilde*Sdotxi_pphi*pdotn - Sdotn*expmu*expnu*pdotxir_pphi - Sdotn_pphi*expmu*expnu*pdotxir) + expmu*expnuprm_r*pdotxir_pphi*(Btilde*Jtilde*Sdotxi*pdotn - Sdotn*expmu*expnu*pdotxir) + expmuprm_r*expnu*pdotxir*(Btilde*Jtilde*Sdotxi*pdotn_pphi + Btilde*Jtilde*Sdotxi_pphi*pdotn - Sdotn*expmu*expnu*pdotxir_pphi - Sdotn_pphi*expmu*expnu*pdotxir) + expmuprm_r*expnu*pdotxir_pphi*(Btilde*Jtilde*Sdotxi*pdotn - Sdotn*expmu*expnu*pdotxir)
    HssTerm3coeff_pphiprm_r = omegacostheta*(-Q_pphiprm_r - Q_pphiprm_r/(2*np.sqrt(Q)) + Q_pphi*Qprm_r/(4*Q**(3/2)))/(2*Btilde*exp2mu*expmu*expnu*(np.sqrt(Q) + Q)**2) + omegacostheta*(-Q_pphi - Q_pphi/(2*np.sqrt(Q)))*(-2*Qprm_r - Qprm_r/np.sqrt(Q))/(2*Btilde*exp2mu*expmu*expnu*(np.sqrt(Q) + Q)**3) + omegacosthetaprm_r*(-Q_pphi - Q_pphi/(2*np.sqrt(Q)))/(2*Btilde*exp2mu*expmu*expnu*(np.sqrt(Q) + Q)**2) - expnuprm_r*omegacostheta*(-Q_pphi - Q_pphi/(2*np.sqrt(Q)))/(2*Btilde*exp2mu*expmu*expnu**2*(np.sqrt(Q) + Q)**2) - expmuprm_r*omegacostheta*(-Q_pphi - Q_pphi/(2*np.sqrt(Q)))/(2*Btilde*exp2mu*expmu**2*expnu*(np.sqrt(Q) + Q)**2) - exp2muprm_r*omegacostheta*(-Q_pphi - Q_pphi/(2*np.sqrt(Q)))/(2*Btilde*exp2mu**2*expmu*expnu*(np.sqrt(Q) + Q)**2) - Btildeprm_r*omegacostheta*(-Q_pphi - Q_pphi/(2*np.sqrt(Q)))/(2*Btilde**2*exp2mu*expmu*expnu*(np.sqrt(Q) + Q)**2)
    HssTerm2_pphiprm_r = Btilde**2*xisq*(Jtilde*pdotn*(-Jtilde*Sdotv*pdotn_pphiprm_r - Jtilde*Sdotv_pphi*pdotnprm_r - Jtilde*Sdotv_pphiprm_r*pdotn - Jtilde*Sdotvprm_r*pdotn_pphi - Jtildeprm_r*Sdotv*pdotn_pphi - Jtildeprm_r*Sdotv_pphi*pdotn + Sdotn*pdotvr_pphiprm_r + Sdotn_pphi*pdotvrprm_r + Sdotn_pphiprm_r*pdotvr + Sdotnprm_r*pdotvr_pphi) + Jtilde*pdotn_pphi*(-Jtilde*Sdotv*pdotnprm_r - Jtilde*Sdotvprm_r*pdotn - Jtildeprm_r*Sdotv*pdotn + Sdotn*pdotvrprm_r + Sdotnprm_r*pdotvr) + Jtilde*pdotn_pphiprm_r*(-Jtilde*Sdotv*pdotn + Sdotn*pdotvr) + Jtilde*pdotnprm_r*(-Jtilde*Sdotv*pdotn_pphi - Jtilde*Sdotv_pphi*pdotn + Sdotn*pdotvr_pphi + Sdotn_pphi*pdotvr) + Jtildeprm_r*pdotn*(-Jtilde*Sdotv*pdotn_pphi - Jtilde*Sdotv_pphi*pdotn + Sdotn*pdotvr_pphi + Sdotn_pphi*pdotvr) + Jtildeprm_r*pdotn_pphi*(-Jtilde*Sdotv*pdotn + Sdotn*pdotvr) + Sdotv*exp2mu*(Q_pphiprm_r + Q_pphiprm_r/(2*np.sqrt(Q)) - Q_pphi*Qprm_r/(4*Q**(3/2))) + Sdotv*exp2muprm_r*(Q_pphi + Q_pphi/(2*np.sqrt(Q))) + Sdotv_pphi*exp2mu*(Qprm_r + Qprm_r/(2*np.sqrt(Q))) + Sdotv_pphi*exp2muprm_r*(np.sqrt(Q) + Q) + Sdotv_pphiprm_r*exp2mu*(np.sqrt(Q) + Q) + Sdotvprm_r*exp2mu*(Q_pphi + Q_pphi/(2*np.sqrt(Q)))) + Btilde*Btildeprm_r*xisq*(2*Jtilde*pdotn*(-Jtilde*Sdotv*pdotn_pphi - Jtilde*Sdotv_pphi*pdotn + Sdotn*pdotvr_pphi + Sdotn_pphi*pdotvr) + 2*Jtilde*pdotn_pphi*(-Jtilde*Sdotv*pdotn + Sdotn*pdotvr) + 2*Sdotv*exp2mu*(Q_pphi + Q_pphi/(2*np.sqrt(Q))) + 2*Sdotv_pphi*exp2mu*(np.sqrt(Q) + Q)) + expmu*pdotxir*(-Btilde*Sdotxi*expnu*pdotvr_pphiprm_r - Btilde*Sdotxi*expnuprm_r*pdotvr_pphi - Btilde*Sdotxi_pphi*expnu*pdotvrprm_r - Btilde*Sdotxi_pphi*expnuprm_r*pdotvr - Btilde*Sdotxi_pphiprm_r*expnu*pdotvr - Btilde*Sdotxiprm_r*expnu*pdotvr_pphi - Btildeprm_r*Sdotxi*expnu*pdotvr_pphi - Btildeprm_r*Sdotxi_pphi*expnu*pdotvr + Sdotv*exp2nu*expmu*pdotxir_pphiprm_r + Sdotv*exp2nu*expmuprm_r*pdotxir_pphi + Sdotv*exp2nuprm_r*expmu*pdotxir_pphi + Sdotv_pphi*exp2nu*expmu*pdotxirprm_r + Sdotv_pphi*exp2nu*expmuprm_r*pdotxir + Sdotv_pphi*exp2nuprm_r*expmu*pdotxir + Sdotv_pphiprm_r*exp2nu*expmu*pdotxir + Sdotvprm_r*exp2nu*expmu*pdotxir_pphi) + expmu*pdotxir_pphi*(-Btilde*Sdotxi*expnu*pdotvrprm_r - Btilde*Sdotxi*expnuprm_r*pdotvr - Btilde*Sdotxiprm_r*expnu*pdotvr - Btildeprm_r*Sdotxi*expnu*pdotvr + Sdotv*exp2nu*expmu*pdotxirprm_r + Sdotv*exp2nu*expmuprm_r*pdotxir + Sdotv*exp2nuprm_r*expmu*pdotxir + Sdotvprm_r*exp2nu*expmu*pdotxir) + expmu*pdotxir_pphiprm_r*(-Btilde*Sdotxi*expnu*pdotvr + Sdotv*exp2nu*expmu*pdotxir) + expmu*pdotxirprm_r*(-Btilde*Sdotxi*expnu*pdotvr_pphi - Btilde*Sdotxi_pphi*expnu*pdotvr + Sdotv*exp2nu*expmu*pdotxir_pphi + Sdotv_pphi*exp2nu*expmu*pdotxir) + expmuprm_r*pdotxir*(-Btilde*Sdotxi*expnu*pdotvr_pphi - Btilde*Sdotxi_pphi*expnu*pdotvr + Sdotv*exp2nu*expmu*pdotxir_pphi + Sdotv_pphi*exp2nu*expmu*pdotxir) + expmuprm_r*pdotxir_pphi*(-Btilde*Sdotxi*expnu*pdotvr + Sdotv*exp2nu*expmu*pdotxir)
    HssTerm2coeff_pphiprm_r = Jtilde*omegar*(-Q_pphiprm_r - Q_pphiprm_r/(2*np.sqrt(Q)) + Q_pphi*Qprm_r/(4*Q**(3/2)))/(2*Btilde*exp2mu*expmu*expnu*xisq*(np.sqrt(Q) + Q)**2) + Jtilde*omegar*(-Q_pphi - Q_pphi/(2*np.sqrt(Q)))*(-2*Qprm_r - Qprm_r/np.sqrt(Q))/(2*Btilde*exp2mu*expmu*expnu*xisq*(np.sqrt(Q) + Q)**3) + Jtilde*omegarprm_r*(-Q_pphi - Q_pphi/(2*np.sqrt(Q)))/(2*Btilde*exp2mu*expmu*expnu*xisq*(np.sqrt(Q) + Q)**2) - Jtilde*expnuprm_r*omegar*(-Q_pphi - Q_pphi/(2*np.sqrt(Q)))/(2*Btilde*exp2mu*expmu*expnu**2*xisq*(np.sqrt(Q) + Q)**2) - Jtilde*expmuprm_r*omegar*(-Q_pphi - Q_pphi/(2*np.sqrt(Q)))/(2*Btilde*exp2mu*expmu**2*expnu*xisq*(np.sqrt(Q) + Q)**2) - Jtilde*exp2muprm_r*omegar*(-Q_pphi - Q_pphi/(2*np.sqrt(Q)))/(2*Btilde*exp2mu**2*expmu*expnu*xisq*(np.sqrt(Q) + Q)**2) + Jtildeprm_r*omegar*(-Q_pphi - Q_pphi/(2*np.sqrt(Q)))/(2*Btilde*exp2mu*expmu*expnu*xisq*(np.sqrt(Q) + Q)**2) - Btildeprm_r*Jtilde*omegar*(-Q_pphi - Q_pphi/(2*np.sqrt(Q)))/(2*Btilde**2*exp2mu*expmu*expnu*xisq*(np.sqrt(Q) + Q)**2)
    HssTerm1_pphiprm_r = SdotSkerrhat_pphi*omegaprm_r + SdotSkerrhat_pphiprm_r*omega
    Hss_pphiprm_r = HssTerm1_pphiprm_r + HssTerm2*HssTerm2coeff_pphiprm_r + HssTerm2_pphi*HssTerm2coeffprm_r + HssTerm2_pphiprm_r*HssTerm2coeff + HssTerm2coeff_pphi*HssTerm2prm_r + HssTerm3*HssTerm3coeff_pphiprm_r + HssTerm3_pphi*HssTerm3coeffprm_r + HssTerm3_pphiprm_r*HssTerm3coeff + HssTerm3coeff_pphi*HssTerm3prm_r
    HsoTerm2c_pphiprm_r = Brtilde*Jtilde*Sdotv*expmu*expnu*pdotxir_pphiprm_r*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotv*expmu*expnuprm_r*pdotxir_pphi*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotv*expmuprm_r*expnu*pdotxir_pphi*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotv_pphi*expmu*expnu*pdotxirprm_r*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotv_pphi*expmu*expnuprm_r*pdotxir*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotv_pphi*expmuprm_r*expnu*pdotxir*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotv_pphiprm_r*expmu*expnu*pdotxir*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotvprm_r*expmu*expnu*pdotxir_pphi*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Q_pphi*Sdotv*expmu*expnu*pdotxirprm_r/(2*np.sqrt(Q)) + Brtilde*Jtilde*Q_pphi*Sdotv*expmu*expnuprm_r*pdotxir/(2*np.sqrt(Q)) + Brtilde*Jtilde*Q_pphi*Sdotv*expmuprm_r*expnu*pdotxir/(2*np.sqrt(Q)) + Brtilde*Jtilde*Q_pphi*Sdotvprm_r*expmu*expnu*pdotxir/(2*np.sqrt(Q)) + Brtilde*Jtilde*Q_pphiprm_r*Sdotv*expmu*expnu*pdotxir/(2*np.sqrt(Q)) + Brtilde*Jtilde*Qprm_r*Sdotv*expmu*expnu*pdotxir_pphi/(2*np.sqrt(Q)) + Brtilde*Jtilde*Qprm_r*Sdotv_pphi*expmu*expnu*pdotxir/(2*np.sqrt(Q)) - Brtilde*Jtilde*Q_pphi*Qprm_r*Sdotv*expmu*expnu*pdotxir/(4*Q**(3/2)) + Brtilde*Jtildeprm_r*Sdotv*expmu*expnu*pdotxir_pphi*(np.sqrt(Q) + 1) + Brtilde*Jtildeprm_r*Sdotv_pphi*expmu*expnu*pdotxir*(np.sqrt(Q) + 1) + Brtilde*Jtildeprm_r*Q_pphi*Sdotv*expmu*expnu*pdotxir/(2*np.sqrt(Q)) + Brtildeprm_r*Jtilde*Sdotv*expmu*expnu*pdotxir_pphi*(np.sqrt(Q) + 1) + Brtildeprm_r*Jtilde*Sdotv_pphi*expmu*expnu*pdotxir*(np.sqrt(Q) + 1) + Brtildeprm_r*Jtilde*Q_pphi*Sdotv*expmu*expnu*pdotxir/(2*np.sqrt(Q))
    HsoTerm2b_pphiprm_r = Btilde*expmu*expnu*pdotxir*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv_pphi*nurprm_r + Jtilde*Sdotv_pphiprm_r*nur + Jtildeprm_r*Sdotv_pphi*nur - Sdotn_pphi*nucosthetaprm_r*xisq - Sdotn_pphiprm_r*nucostheta*xisq) + Btilde*expmu*expnu*pdotxir_pphi*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv*nurprm_r + Jtilde*Sdotvprm_r*nur + Jtildeprm_r*Sdotv*nur - Sdotn*nucosthetaprm_r*xisq - Sdotnprm_r*nucostheta*xisq) + Btilde*expmu*expnu*pdotxir_pphiprm_r*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq) + Btilde*expmu*expnu*pdotxirprm_r*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv_pphi*nur - Sdotn_pphi*nucostheta*xisq) + Btilde*expmu*expnuprm_r*pdotxir*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv_pphi*nur - Sdotn_pphi*nucostheta*xisq) + Btilde*expmu*expnuprm_r*pdotxir_pphi*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq) + Btilde*expmuprm_r*expnu*pdotxir*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv_pphi*nur - Sdotn_pphi*nucostheta*xisq) + Btilde*expmuprm_r*expnu*pdotxir_pphi*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq) + Btilde*Q_pphi*expmu*expnu*pdotxir*(Jtilde*Sdotv*nurprm_r + Jtilde*Sdotvprm_r*nur + Jtildeprm_r*Sdotv*nur - Sdotn*nucosthetaprm_r*xisq - Sdotnprm_r*nucostheta*xisq)/np.sqrt(Q) + Btilde*Q_pphi*expmu*expnu*pdotxirprm_r*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq)/np.sqrt(Q) + Btilde*Q_pphi*expmu*expnuprm_r*pdotxir*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq)/np.sqrt(Q) + Btilde*Q_pphi*expmuprm_r*expnu*pdotxir*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq)/np.sqrt(Q) + Btilde*Q_pphiprm_r*expmu*expnu*pdotxir*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq)/np.sqrt(Q) + Btilde*Qprm_r*expmu*expnu*pdotxir*(Jtilde*Sdotv_pphi*nur - Sdotn_pphi*nucostheta*xisq)/np.sqrt(Q) + Btilde*Qprm_r*expmu*expnu*pdotxir_pphi*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq)/np.sqrt(Q) - Btilde*Q_pphi*Qprm_r*expmu*expnu*pdotxir*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq)/(2*Q**(3/2)) + Btildeprm_r*expmu*expnu*pdotxir*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv_pphi*nur - Sdotn_pphi*nucostheta*xisq) + Btildeprm_r*expmu*expnu*pdotxir_pphi*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq) + Btildeprm_r*Q_pphi*expmu*expnu*pdotxir*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq)/np.sqrt(Q)
    HsoTerm2a_pphiprm_r = Btilde**2*Jtilde*Sdotxi*(-np.sqrt(Q)*(nur*pdotvr_pphiprm_r + nurprm_r*pdotvr_pphi + pdotn_pphi*xisq*(mucosthetaprm_r - nucosthetaprm_r) + pdotn_pphiprm_r*xisq*(mucostheta - nucostheta)) - mucostheta*pdotn_pphiprm_r*xisq - mucosthetaprm_r*pdotn_pphi*xisq + mur*pdotvr_pphiprm_r*(np.sqrt(Q) + 1) + murprm_r*pdotvr_pphi*(np.sqrt(Q) + 1) + Q_pphi*mur*pdotvrprm_r/(2*np.sqrt(Q)) + Q_pphi*murprm_r*pdotvr/(2*np.sqrt(Q)) + Q_pphi*(-nur*pdotvrprm_r - nurprm_r*pdotvr + pdotn*xisq*(-mucosthetaprm_r + nucosthetaprm_r) + pdotnprm_r*xisq*(-mucostheta + nucostheta))/(2*np.sqrt(Q)) + Q_pphiprm_r*mur*pdotvr/(2*np.sqrt(Q)) + Q_pphiprm_r*(-nur*pdotvr + pdotn*xisq*(-mucostheta + nucostheta))/(2*np.sqrt(Q)) + Qprm_r*mur*pdotvr_pphi/(2*np.sqrt(Q)) - Qprm_r*(nur*pdotvr_pphi + pdotn_pphi*xisq*(mucostheta - nucostheta))/(2*np.sqrt(Q)) - Q_pphi*Qprm_r*mur*pdotvr/(4*Q**(3/2)) - Q_pphi*Qprm_r*(-nur*pdotvr + pdotn*xisq*(-mucostheta + nucostheta))/(4*Q**(3/2))) + Btilde**2*Jtilde*Sdotxi_pphi*(np.sqrt(Q)*(-nur*pdotvrprm_r - nurprm_r*pdotvr + pdotn*xisq*(-mucosthetaprm_r + nucosthetaprm_r) + pdotnprm_r*xisq*(-mucostheta + nucostheta)) - mucostheta*pdotnprm_r*xisq - mucosthetaprm_r*pdotn*xisq + mur*pdotvrprm_r*(np.sqrt(Q) + 1) + murprm_r*pdotvr*(np.sqrt(Q) + 1) + Qprm_r*mur*pdotvr/(2*np.sqrt(Q)) + Qprm_r*(-nur*pdotvr + pdotn*xisq*(-mucostheta + nucostheta))/(2*np.sqrt(Q))) + Btilde**2*Jtilde*Sdotxi_pphiprm_r*(np.sqrt(Q)*(-nur*pdotvr + pdotn*xisq*(-mucostheta + nucostheta)) - mucostheta*pdotn*xisq + mur*pdotvr*(np.sqrt(Q) + 1)) + Btilde**2*Jtilde*Sdotxiprm_r*(-np.sqrt(Q)*(nur*pdotvr_pphi + pdotn_pphi*xisq*(mucostheta - nucostheta)) - mucostheta*pdotn_pphi*xisq + mur*pdotvr_pphi*(np.sqrt(Q) + 1) + Q_pphi*mur*pdotvr/(2*np.sqrt(Q)) + Q_pphi*(-nur*pdotvr + pdotn*xisq*(-mucostheta + nucostheta))/(2*np.sqrt(Q))) + Btilde**2*Jtildeprm_r*Sdotxi*(-np.sqrt(Q)*(nur*pdotvr_pphi + pdotn_pphi*xisq*(mucostheta - nucostheta)) - mucostheta*pdotn_pphi*xisq + mur*pdotvr_pphi*(np.sqrt(Q) + 1) + Q_pphi*mur*pdotvr/(2*np.sqrt(Q)) + Q_pphi*(-nur*pdotvr + pdotn*xisq*(-mucostheta + nucostheta))/(2*np.sqrt(Q))) + Btilde**2*Jtildeprm_r*Sdotxi_pphi*(np.sqrt(Q)*(-nur*pdotvr + pdotn*xisq*(-mucostheta + nucostheta)) - mucostheta*pdotn*xisq + mur*pdotvr*(np.sqrt(Q) + 1)) + Btilde*Btildeprm_r*Jtilde*Sdotxi*(-2*np.sqrt(Q)*(nur*pdotvr_pphi + pdotn_pphi*xisq*(mucostheta - nucostheta)) - 2*mucostheta*pdotn_pphi*xisq + 2*mur*pdotvr_pphi*(np.sqrt(Q) + 1) + Q_pphi*mur*pdotvr/np.sqrt(Q) + Q_pphi*(-nur*pdotvr + pdotn*xisq*(-mucostheta + nucostheta))/np.sqrt(Q)) + Btilde*Btildeprm_r*Jtilde*Sdotxi_pphi*(2*np.sqrt(Q)*(-nur*pdotvr + pdotn*xisq*(-mucostheta + nucostheta)) - 2*mucostheta*pdotn*xisq + 2*mur*pdotvr*(np.sqrt(Q) + 1))
    HsoTerm2_pphiprm_r = HsoTerm2a_pphiprm_r + HsoTerm2b_pphiprm_r - HsoTerm2c_pphiprm_r
    HsoTerm2coeff_pphiprm_r = expnu*(-Q_pphiprm_r - Q_pphiprm_r/(2*np.sqrt(Q)) + Q_pphi*Qprm_r/(4*Q**(3/2)))/(Btilde**2*exp2mu*xisq*(np.sqrt(Q) + Q)**2) + expnu*(-Q_pphi - Q_pphi/(2*np.sqrt(Q)))*(-2*Qprm_r - Qprm_r/np.sqrt(Q))/(Btilde**2*exp2mu*xisq*(np.sqrt(Q) + Q)**3) + expnuprm_r*(-Q_pphi - Q_pphi/(2*np.sqrt(Q)))/(Btilde**2*exp2mu*xisq*(np.sqrt(Q) + Q)**2) - exp2muprm_r*expnu*(-Q_pphi - Q_pphi/(2*np.sqrt(Q)))/(Btilde**2*exp2mu**2*xisq*(np.sqrt(Q) + Q)**2) - Btildeprm_r*expnu*(-2*Q_pphi - Q_pphi/np.sqrt(Q))/(Btilde**3*exp2mu*xisq*(np.sqrt(Q) + Q)**2)
    HsoTerm1_pphiprm_r = SdotSkerrhat*exp2nu*pdotxir_pphi*(-Btildeprm_r + expmu*expnuprm_r + expmuprm_r*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) + SdotSkerrhat*exp2nu*pdotxir_pphiprm_r*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) - SdotSkerrhat*exp2nu*expmuprm_r*pdotxir_pphi*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu**2*xisq) + SdotSkerrhat*exp2nuprm_r*pdotxir_pphi*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) + SdotSkerrhat_pphi*exp2nu*pdotxir*(-Btildeprm_r + expmu*expnuprm_r + expmuprm_r*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) + SdotSkerrhat_pphi*exp2nu*pdotxirprm_r*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) - SdotSkerrhat_pphi*exp2nu*expmuprm_r*pdotxir*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu**2*xisq) + SdotSkerrhat_pphi*exp2nuprm_r*pdotxir*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) + SdotSkerrhat_pphiprm_r*exp2nu*pdotxir*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) + SdotSkerrhatprm_r*exp2nu*pdotxir_pphi*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) - Q_pphi*SdotSkerrhat*exp2nu*pdotxir*(-Btildeprm_r + expmu*expnuprm_r + expmuprm_r*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq) - Q_pphi*SdotSkerrhat*exp2nu*pdotxirprm_r*(-Btilde + expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq) + Q_pphi*SdotSkerrhat*exp2nu*expmuprm_r*pdotxir*(-Btilde + expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu**2*xisq) - Q_pphi*SdotSkerrhat*exp2nuprm_r*pdotxir*(-Btilde + expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq) - Q_pphi*SdotSkerrhatprm_r*exp2nu*pdotxir*(-Btilde + expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq) - Q_pphiprm_r*SdotSkerrhat*exp2nu*pdotxir*(-Btilde + expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq) - Qprm_r*SdotSkerrhat*exp2nu*pdotxir_pphi*(-Btilde + expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq) - Qprm_r*SdotSkerrhat_pphi*exp2nu*pdotxir*(-Btilde + expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq) + Q_pphi*Qprm_r*SdotSkerrhat*exp2nu*pdotxir*(-3*Btilde + 3*expmu*expnu)/(4*Btilde**2*Q**(5/2)*expmu*xisq) - Btildeprm_r*SdotSkerrhat*exp2nu*pdotxir_pphi*(-2*Btilde + 2*expmu*expnu)/(Btilde**3*np.sqrt(Q)*expmu*xisq) - Btildeprm_r*SdotSkerrhat_pphi*exp2nu*pdotxir*(-2*Btilde + 2*expmu*expnu)/(Btilde**3*np.sqrt(Q)*expmu*xisq) + Btildeprm_r*Q_pphi*SdotSkerrhat*exp2nu*pdotxir*(-Btilde + expmu*expnu)/(Btilde**3*Q**(3/2)*expmu*xisq)
    Hso_pphiprm_r = HsoTerm1_pphiprm_r + HsoTerm2*HsoTerm2coeff_pphiprm_r + HsoTerm2_pphi*HsoTerm2coeffprm_r + HsoTerm2_pphiprm_r*HsoTerm2coeff + HsoTerm2coeff_pphi*HsoTerm2prm_r
    Hd_pphiprm_r = Hdcoeff*Hdsum_pphiprm_r + Hdcoeffprm_r*Hdsum_pphi
    Hns_pphiprm_r = betapsum_pphiprm_r + Hnsradicand_pphi*alphaprm_r/(2*np.sqrt(Hnsradicand)) + Hnsradicand_pphiprm_r*alpha/(2*np.sqrt(Hnsradicand)) - Hnsradicand_pphi*Hnsradicandprm_r*alpha/(4*Hnsradicand**(3/2))
    Hs_pphiprm_r = Hso_pphiprm_r + Hss_pphiprm_r
    Heff_pphiprm_r = -Hd_pphiprm_r + Hns_pphiprm_r + Hs_pphiprm_r
    Hreal_pphiprm_r = -Heff_pphi*Heffprm_r*eta**2/(2*eta*(Heff - 1) + 1)**(3/2) + Heff_pphiprm_r*eta/np.sqrt(2*eta*(Heff - 1) + 1)
    return np.array([Hreal_pphiprm_r])