from __future__ import division
import numpy as np
def compute_d2Hdrdpphi(m1, m2, eta, r, theta, phi, pr, ptheta, pphi, S1r, S1theta, S1phi, S2r, S2theta, S2phi, KK, k0, k1, dSO, dSS, tortoise, EMgamma):
    M = m1+m2
    mu = m1*m2/M
    eta = mu/M
    u = 1/r
    sigmastar3 = m2/m1*S1phi+m1/m2*S2phi
    sigmastar2 = m2/m1*S1theta+m1/m2*S2theta
    sigmastar1 = m2/m1*S1r+m1/m2*S2r
    sigma3 = S1phi+S2phi##Sid:Snp.pinsshouldbeinpolardirections
    sigma2 = S1theta+S2theta
    sigma1 = S1r+S2r
    Skerr3 = sigma3##Sid:Snp.pinsshouldbeinpolardirections
    Skerr2 = sigma2
    Skerr1 = sigma1
    Skerrmag = np.sqrt(Skerr1*Skerr1+Skerr2*Skerr2+Skerr3*Skerr3)
    Skerrhat3 = Skerr3/Skerrmag
    Skerrhat2 = Skerr2/Skerrmag
    Skerrhat1 = Skerr1/Skerrmag
    a = Skerrmag
    n3 = 0
    n2 = 0
    n1 = 1
    e33 = Skerrhat3##Sid:insphericalpolar,nisjust(1,0,0)
    e32 = Skerrhat2
    e31 = Skerrhat1
    xi3 = e31*n2-e32*n1
    xi2 = e33*n1-e31*n3
    xi1 = e32*n3-e33*n2
    v3 = n1*xi2-n2*xi1##Sid:Testingoutatypohere
    v2 = n3*xi1-n1*xi3
    v1 = n2*xi3-n3*xi2
    costhetaBL = e31*n1+e32*n2+e33*n3
    sin2thetaBL = 1-costhetaBL*costhetaBL
    xisq = sin2thetaBL
    w2 = a*a+r*r
    Sigma = r*r+a*a*costhetaBL*costhetaBL
    sintheta = np.sin(theta)##Sid:costhetaBLsubstitution
    Dinv = 1+np.log(1+6*eta*u*u+2*(26-3*eta)*eta*u*u*u)
    omegatilde = 2*a*r
    K = 1.712-1.803949138004582*eta-39.77229225266885*eta*eta+103.16588921239249*eta*eta*eta
    etaKminus1 = eta*K-1
    Delta0 = K*(eta*K-2)
    Delta1 = -2*etaKminus1*(K+Delta0)
    Delta2 = np.true_divide(1,2)*Delta1*(Delta1-4*etaKminus1)-a*a*etaKminus1*etaKminus1*Delta0
    Delta3 = -np.true_divide(1,3)*Delta1*Delta1*Delta1+etaKminus1*Delta1*Delta1+Delta2*Delta1-2*etaKminus1*(Delta2-etaKminus1)-a*a*etaKminus1*etaKminus1*Delta1
    Delta4 = np.true_divide(1,12)*(6*a*a*(Delta1*Delta1-2*Delta2)*etaKminus1*etaKminus1+3*Delta1*Delta1*Delta1*Delta1-8*etaKminus1*Delta1*Delta1*Delta1-12*Delta2*Delta1*Delta1+12*(2*etaKminus1*Delta2+Delta3)*Delta1+12*(np.true_divide(94,3)-np.true_divide(41,32)*np.pi*np.pi)*etaKminus1*etaKminus1+6*(Delta2*Delta2-4*Delta3*etaKminus1))
    Delta5 = etaKminus1*etaKminus1*((np.true_divide(-4237,60)+np.true_divide(128,5)*EMgamma+np.true_divide(2275,512)*np.pi*np.pi-np.true_divide(1,3)*a*a*(Delta1*Delta1*Delta1-3*Delta1*Delta2+3*Delta3)-(Delta1*Delta1*Delta1*Delta1*Delta1-5*Delta1*Delta1*Delta1*Delta2+5*Delta1*Delta2*Delta2+5*Delta1*Delta1*Delta3-5*Delta2*Delta3-5*Delta1*Delta4)/(5*etaKminus1*etaKminus1)+(Delta1*Delta1*Delta1*Delta1-4*Delta1*Delta1*Delta2+2*Delta2*Delta2+4*Delta1*Delta3-4*Delta4)/(2*etaKminus1)+np.true_divide(256,5)*np.log(2)))
    Delta5l = etaKminus1*etaKminus1*np.true_divide(64,5)
    logarg = u*(Delta1+u*(Delta2+u*(Delta3+u*(Delta4+u*(Delta5+Delta5l*np.log(u))))))
    Deltaucalib = 1+eta*(Delta0+np.log(1+logarg))
    Deltaucalibprime = -eta*u*u*(Delta1+u*(2*Delta2+u*(3*Delta3+u*(4*Delta4+u*(5*(Delta5+Delta5l*np.log(u)))))))/(1+logarg)
    Deltaubar = a*a*u*u+(2*u+1/etaKminus1)/etaKminus1
    Deltaubarprime = -2*a*a*u*u*u-2*u*u/(etaKminus1)
    Deltau = Deltaubar*Deltaucalib
    Deltauprime = Deltaubarprime*Deltaucalib+Deltaubar*Deltaucalibprime
    Deltatprime = 2*r*Deltau+r*r*Deltauprime
    Deltat = r*r*Deltau
    Deltar = Deltat*Dinv
    Lambt = w2*w2-a*a*Deltat*sin2thetaBL
    csi = np.sqrt(Deltar*Deltat)/w2##Sid:sin2thetaBLsubstitution
    csi1 = 1+(1-abs(1-tortoise))*(csi-1)
    csi2 = 1+(np.true_divide(1,2)-np.true_divide(1,2)*np.sign(np.true_divide(3,2)-tortoise))*(csi-1)
    prT = csi2*(pr*n1+ptheta*n2/r+pphi*n3/r/sintheta)
    phat3 = pphi/r/sintheta+prT*(1-1/csi1)*n3##Sid:Rewritewithsphericalmomenta
    phat2 = ptheta/r+prT*(1-1/csi1)*n2
    phat1 = pr+prT*(1-1/csi1)*n1
    pdotxir = (phat1*xi1+phat2*xi2+phat3*xi3)*r##Sid:Rewritewithsphericalmomenta
    pdotn = phat1*n1+phat2*n2+phat3*n3
    pdotvr = (phat1*v1+phat2*v2+phat3*v3)*r
    Qcoeff2 = 1/(Sigma*sin2thetaBL)
    Qcoeff1 = Sigma/(Lambt*sin2thetaBL)##Sid:sin2thetaBLsubstitution
    DrSipn2 = Deltar*pdotn*pdotn/Sigma##Sid:sin2thetaBLsubstitution
    Q = 1+DrSipn2+Qcoeff1*pdotxir*pdotxir+Qcoeff2*pdotvr*pdotvr
    Qminus1 = Q-1
    Jtilde = np.sqrt(Deltar)
    exp2mu = Sigma
    expmu = np.sqrt(exp2mu)
    Brtilde = (np.sqrt(Deltar)*Deltatprime-2*Deltat)/(2*np.sqrt(Deltar*Deltat))
    Btilde = np.sqrt(Deltat)
    exp2nu = Deltat*Sigma/Lambt
    expnu = np.sqrt(exp2nu)
    omega = omegatilde/Lambt
    omegatildeprime = 2*a
    Lambtprime = 4*(a*a+r*r)*r-2*a*a*Deltatprime*sin2thetaBL
    mucostheta = a*a*costhetaBL/Sigma##Sid:sin2thetaBLsubstitution
    nucostheta = a*a*w2*costhetaBL*(w2-Deltat)/(Lambt*Sigma)##Sid:costhetaBLsubstitution
    omegacostheta = -2*a*a*costhetaBL*Deltat*omegatilde/(Lambt*Lambt)##Sid:costhetaBLsubstitution
    mur = r/Sigma-1/np.sqrt(Deltar)##Sid:costhetaBLsubstitution
    nur = r/Sigma+w2*(w2*Deltatprime-4*r*Deltat)/(2*Lambt*Deltat)
    omegar = (Lambt*omegatildeprime-Lambtprime*omegatilde)/(Lambt*Lambt)
    dSO = -74.71-156.*eta+627.5*eta*eta
    sigmacoeffTerm3 = eta*dSO*u*u*u
    sigmacoeffTerm2 = eta/(144*r*r)*(-896+r*(-436*Qminus1-96*DrSipn2+r*(-45*Qminus1*Qminus1+36*Qminus1*DrSipn2))+eta*(-336+r*(204*Qminus1-882*DrSipn2+r*(810*DrSipn2*DrSipn2-234*Qminus1*DrSipn2))))
    sigmacoeffTerm1 = eta/12*(-8*u+3*Qminus1-36*DrSipn2)
    sigmacoeff = sigmacoeffTerm1+sigmacoeffTerm2+sigmacoeffTerm3##Sid:Again,multiplybyuinstead
    sigmastarcoeffTerm2 = eta/(72*r*r)*(706+r*(-206*Qminus1+282*DrSipn2+r*Qminus1*(96*DrSipn2-23*Qminus1))+eta*(-54+r*(120*Qminus1-324*DrSipn2+r*(360*DrSipn2*DrSipn2+Qminus1*(-126*DrSipn2-3*Qminus1)))))
    sigmastarcoeffTerm1 = eta/12*(14*u+4*Qminus1-30*DrSipn2)
    sigmastarcoeff = sigmastarcoeffTerm1+sigmastarcoeffTerm2##Sid:Multiplybyuoncemore
    Deltasigmastar3 = sigmastar3*sigmastarcoeff+sigma3*sigmacoeff
    Deltasigmastar2 = sigmastar2*sigmastarcoeff+sigma2*sigmacoeff
    Deltasigmastar1 = sigmastar1*sigmastarcoeff+sigma1*sigmacoeff
    Sstar3 = sigmastar3+Deltasigmastar3
    Sstar2 = sigmastar2+Deltasigmastar2
    Sstar1 = sigmastar1+Deltasigmastar1
    S3 = Sstar3
    S2 = Sstar2
    S1 = Sstar1
    Sstardotn = Sstar1*n1+Sstar2*n2+Sstar3*n3
    SdotSkerrhat = S1*Skerrhat1+S2*Skerrhat2+S3*Skerrhat3
    Sdotn = S1*n1+S2*n2+S3*n3
    Sdotv = S1*v1+S2*v2+S3*v3
    Sdotxi = S1*xi1+S2*xi2+S3*xi3
    HdsumTerm2 = 3*Sstardotn*Sstardotn
    HdsumTerm1 = Sstar1*Sstar1+Sstar2*Sstar2+Sstar3*Sstar3
    Hdsum = HdsumTerm1-HdsumTerm2
    Hdcoeff = np.true_divide(1,2)*(u*u*u)
    Q4 = 2*prT*prT*prT*prT*u*u*(4-3*eta)*eta##Sid:Whydividebyrwhenyoucanmultiplybyu?
    gammappsum = Deltar/Sigma*pdotn*pdotn+1/Sigma*pdotvr*pdotvr/sin2thetaBL+Sigma/Lambt/sin2thetaBL*pdotxir*pdotxir
    Hnsradicand = 1+gammappsum+Q4##Sid:sin2thetaBLsubstitution
    alpha = np.sqrt(Deltat*Sigma/Lambt)
    betapsum = omegatilde*pdotxir/Lambt
    HssTerm3 = expmu*expnu*pdotxir*(Jtilde*pdotn*Sdotxi*Btilde-expmu*expnu*pdotxir*Sdotn)+(pdotvr*(Sdotn*pdotvr-Jtilde*pdotn*Sdotv)-exp2mu*(np.sqrt(Q)+Q)*Sdotn*xisq)*Btilde*Btilde##Sid:Changedtopdotxirtoeliminatepphi
    HssTerm3coeff = omegacostheta/(2*exp2mu*expmu*expnu*Btilde*(Q+np.sqrt(Q)))
    HssTerm2 = expmu*pdotxir*(expmu*exp2nu*pdotxir*Sdotv-expnu*pdotvr*Sdotxi*Btilde)+xisq*Btilde*Btilde*(exp2mu*(np.sqrt(Q)+Q)*Sdotv+Jtilde*pdotn*(pdotvr*Sdotn-Jtilde*pdotn*Sdotv))
    HssTerm2coeff = Jtilde*omegar/(2*exp2mu*expmu*expnu*Btilde*(Q+np.sqrt(Q))*xisq)
    HssTerm1 = omega*SdotSkerrhat
    Hss = HssTerm1+HssTerm2coeff*HssTerm2+HssTerm3coeff*HssTerm3
    HsoTerm2c = Jtilde*Brtilde*expmu*expnu*pdotxir*(np.sqrt(Q)+1)*Sdotv
    HsoTerm2b = expmu*expnu*pdotxir*(2*np.sqrt(Q)+1)*(Jtilde*nur*Sdotv-nucostheta*Sdotn*xisq)*Btilde
    HsoTerm2a = Sdotxi*Jtilde*(mur*pdotvr*(np.sqrt(Q)+1)-mucostheta*pdotn*xisq-np.sqrt(Q)*(nur*pdotvr+(mucostheta-nucostheta)*pdotn*xisq))*Btilde*Btilde
    HsoTerm2 = HsoTerm2a+HsoTerm2b-HsoTerm2c
    HsoTerm2coeff = expnu/(exp2mu*Btilde*Btilde*(Q+np.sqrt(Q))*xisq)
    HsoTerm1 = exp2nu*(expmu*expnu-Btilde)*pdotxir*SdotSkerrhat/(expmu*Btilde*Btilde*np.sqrt(Q)*xisq)
    Hso = HsoTerm1+HsoTerm2coeff*HsoTerm2
    Hd = Hdcoeff*Hdsum
    Hns = betapsum+alpha*np.sqrt(Hnsradicand)
    Hs = Hso+Hss
    dSS = 8.127-154.2*eta+830.8*eta*eta
    Heff = Hs+Hns-Hd+dSS*eta*u*u*u*u*(S1r*S1r+S1theta*S1theta+S1phi*S1phi+S2r*S2r+S2theta*S2theta+S2phi*S2phi)
    u_r = -1/r**2
    w2_r = 2*r
    Sigma_r = 2*r
    Dinv_r = (3*eta*u**2*u_r*(-6*eta+52)+12*eta*u*u_r)/(eta*u**3*(-6*eta+52)+6*eta*u**2+1)
    omegatilde_r = 2*a
    logarg_r = u*(u*(u*(u*(Delta5l*u_r+u_r*(Delta5+Delta5l*np.log(u)))+u_r*(Delta4+u*(Delta5+Delta5l*np.log(u))))+u_r*(Delta3+u*(Delta4+u*(Delta5+Delta5l*np.log(u)))))+u_r*(Delta2+u*(Delta3+u*(Delta4+u*(Delta5+Delta5l*np.log(u))))))+u_r*(Delta1+u*(Delta2+u*(Delta3+u*(Delta4+u*(Delta5+Delta5l*np.log(u))))))
    Deltaucalib_r = eta*logarg_r/(logarg+1)
    Deltaucalibprime_r = eta*logarg_r*u**2*(Delta1+u*(2*Delta2+u*(3*Delta3+u*(4*Delta4+u*(5*Delta5+5*Delta5l*np.log(u))))))/(logarg+1)**2-eta*u**2*(u*(u*(u*(5*Delta5l*u_r+u_r*(5*Delta5+5*Delta5l*np.log(u)))+u_r*(4*Delta4+u*(5*Delta5+5*Delta5l*np.log(u))))+u_r*(3*Delta3+u*(4*Delta4+u*(5*Delta5+5*Delta5l*np.log(u)))))+u_r*(2*Delta2+u*(3*Delta3+u*(4*Delta4+u*(5*Delta5+5*Delta5l*np.log(u))))))/(logarg+1)-2*eta*u*u_r*(Delta1+u*(2*Delta2+u*(3*Delta3+u*(4*Delta4+u*(5*Delta5+5*Delta5l*np.log(u))))))/(logarg+1)
    Deltaubar_r = 2*a**2*u*u_r+2*u_r/etaKminus1
    Deltaubarprime_r = -6*a**2*u**2*u_r-4*u*u_r/etaKminus1
    Deltau_r = Deltaubar*Deltaucalib_r+Deltaubar_r*Deltaucalib
    Deltauprime_r = Deltaubar*Deltaucalibprime_r+Deltaubarprime*Deltaucalib_r+Deltaubarprime_r*Deltaucalib+Deltaubar_r*Deltaucalibprime
    Deltatprime_r = 2*Deltau+2*Deltauprime*r+Deltauprime_r*r**2+2*Deltau_r*r
    Deltat_r = 2*Deltau*r+Deltau_r*r**2
    Deltar_r = Deltat*Dinv_r+Deltat_r*Dinv
    Lambt_r = -Deltat_r*a**2*sin2thetaBL+2*w2*w2_r
    csi_r = -w2_r*np.sqrt(Deltar*Deltat)/w2**2+np.sqrt(Deltar*Deltat)*(Deltar*Deltat_r/2+Deltar_r*Deltat/2)/(Deltar*Deltat*w2)
    csi1_r = csi_r*(-abs(-tortoise+1)+1)
    csi2_r = csi_r*(-np.sign(-tortoise+3/2)/2+1/2)
    prT_r = csi2*(-n2*ptheta/r**2-n3*pphi/(r**2*sintheta))+csi2_r*(n1*pr+n2*ptheta/r+n3*pphi/(r*sintheta))
    phat3_r = n3*prT_r*(1-1/csi1)-pphi/(r**2*sintheta)+csi1_r*n3*prT/csi1**2
    phat2_r = n2*prT_r*(1-1/csi1)-ptheta/r**2+csi1_r*n2*prT/csi1**2
    phat1_r = n1*prT_r*(1-1/csi1)+csi1_r*n1*prT/csi1**2
    pdotxir_r = phat1*xi1+phat2*xi2+phat3*xi3+r*(phat1_r*xi1+phat2_r*xi2+phat3_r*xi3)
    pdotn_r = n1*phat1_r+n2*phat2_r+n3*phat3_r
    pdotvr_r = phat1*v1+phat2*v2+phat3*v3+r*(phat1_r*v1+phat2_r*v2+phat3_r*v3)
    Qcoeff2_r = -Sigma_r/(Sigma**2*sin2thetaBL)
    Qcoeff1_r = Sigma_r/(Lambt*sin2thetaBL)-Lambt_r*Sigma/(Lambt**2*sin2thetaBL)
    DrSipn2_r = 2*Deltar*pdotn*pdotn_r/Sigma-Deltar*Sigma_r*pdotn**2/Sigma**2+Deltar_r*pdotn**2/Sigma
    Q_r = DrSipn2_r+2*Qcoeff1*pdotxir*pdotxir_r+Qcoeff1_r*pdotxir**2+2*Qcoeff2*pdotvr*pdotvr_r+Qcoeff2_r*pdotvr**2
    Qminus1_r = Q_r
    Jtilde_r = Deltar_r/(2*np.sqrt(Deltar))
    exp2mu_r = Sigma_r
    expmu_r = exp2mu_r/(2*np.sqrt(exp2mu))
    Brtilde_r = (np.sqrt(Deltar)*Deltatprime_r-2*Deltat_r+Deltar_r*Deltatprime/(2*np.sqrt(Deltar)))/(2*np.sqrt(Deltar*Deltat))+(np.sqrt(Deltar)*Deltatprime-2*Deltat)*(-Deltar*Deltat_r/2-Deltar_r*Deltat/2)/(2*Deltar*Deltat*np.sqrt(Deltar*Deltat))
    Btilde_r = Deltat_r/(2*np.sqrt(Deltat))
    exp2nu_r = Deltat*Sigma_r/Lambt-Deltat*Lambt_r*Sigma/Lambt**2+Deltat_r*Sigma/Lambt
    expnu_r = exp2nu_r/(2*np.sqrt(exp2nu))
    omega_r = omegatilde_r/Lambt-Lambt_r*omegatilde/Lambt**2
    Lambtprime_r = -2*Deltatprime_r*a**2*sin2thetaBL+4*a**2+12*r**2
    mucostheta_r = -Sigma_r*a**2*costhetaBL/Sigma**2
    nucostheta_r = a**2*costhetaBL*w2*(-Deltat_r+w2_r)/(Lambt*Sigma)+a**2*costhetaBL*w2_r*(-Deltat+w2)/(Lambt*Sigma)-Sigma_r*a**2*costhetaBL*w2*(-Deltat+w2)/(Lambt*Sigma**2)-Lambt_r*a**2*costhetaBL*w2*(-Deltat+w2)/(Lambt**2*Sigma)
    omegacostheta_r = -2*Deltat*a**2*costhetaBL*omegatilde_r/Lambt**2+4*Deltat*Lambt_r*a**2*costhetaBL*omegatilde/Lambt**3-2*Deltat_r*a**2*costhetaBL*omegatilde/Lambt**2
    mur_r = 1/Sigma-Sigma_r*r/Sigma**2+Deltar_r/(2*Deltar**(3/2))
    nur_r = 1/Sigma-Sigma_r*r/Sigma**2+w2*(-4*Deltat+Deltatprime*w2_r+Deltatprime_r*w2-4*Deltat_r*r)/(2*Deltat*Lambt)+w2_r*(-4*Deltat*r+Deltatprime*w2)/(2*Deltat*Lambt)-Lambt_r*w2*(-4*Deltat*r+Deltatprime*w2)/(2*Deltat*Lambt**2)-Deltat_r*w2*(-4*Deltat*r+Deltatprime*w2)/(2*Deltat**2*Lambt)
    omegar_r = (-Lambtprime*omegatilde_r-Lambtprime_r*omegatilde+Lambt_r*omegatildeprime)/Lambt**2+Lambt_r*(-2*Lambt*omegatildeprime+2*Lambtprime*omegatilde)/Lambt**3
    sigmacoeffTerm3_r = 3*dSO*eta*u**2*u_r
    sigmacoeffTerm2_r = eta*(-96*DrSipn2-436*Qminus1+eta*(-882*DrSipn2+204*Qminus1+r*(810*DrSipn2**2-234*DrSipn2*Qminus1)+r*(810*DrSipn2**2-234*DrSipn2*Qminus1-882*DrSipn2_r+204*Qminus1_r+r*(1620*DrSipn2*DrSipn2_r-234*DrSipn2*Qminus1_r-234*DrSipn2_r*Qminus1)))+r*(36*DrSipn2*Qminus1-45*Qminus1**2)+r*(36*DrSipn2*Qminus1-96*DrSipn2_r-45*Qminus1**2-436*Qminus1_r+r*(36*DrSipn2*Qminus1_r+36*DrSipn2_r*Qminus1-90*Qminus1*Qminus1_r)))/(144*r**2)-eta*(eta*(r*(-882*DrSipn2+204*Qminus1+r*(810*DrSipn2**2-234*DrSipn2*Qminus1))-336)+r*(-96*DrSipn2-436*Qminus1+r*(36*DrSipn2*Qminus1-45*Qminus1**2))-896)/(72*r**3)
    sigmacoeffTerm1_r = eta*(-36*DrSipn2_r+3*Qminus1_r-8*u_r)/12
    sigmacoeff_r = sigmacoeffTerm1_r+sigmacoeffTerm2_r+sigmacoeffTerm3_r
    sigmastarcoeffTerm2_r = eta*(282*DrSipn2+Qminus1*r*(96*DrSipn2-23*Qminus1)-206*Qminus1+eta*(-324*DrSipn2+120*Qminus1+r*(360*DrSipn2**2+Qminus1*(-126*DrSipn2-3*Qminus1))+r*(360*DrSipn2**2-324*DrSipn2_r+Qminus1*(-126*DrSipn2-3*Qminus1)+120*Qminus1_r+r*(720*DrSipn2*DrSipn2_r+Qminus1*(-126*DrSipn2_r-3*Qminus1_r)+Qminus1_r*(-126*DrSipn2-3*Qminus1))))+r*(282*DrSipn2_r+Qminus1*r*(96*DrSipn2_r-23*Qminus1_r)+Qminus1*(96*DrSipn2-23*Qminus1)+Qminus1_r*r*(96*DrSipn2-23*Qminus1)-206*Qminus1_r))/(72*r**2)-eta*(eta*(r*(-324*DrSipn2+120*Qminus1+r*(360*DrSipn2**2+Qminus1*(-126*DrSipn2-3*Qminus1)))-54)+r*(282*DrSipn2+Qminus1*r*(96*DrSipn2-23*Qminus1)-206*Qminus1)+706)/(36*r**3)
    sigmastarcoeffTerm1_r = eta*(-30*DrSipn2_r+4*Qminus1_r+14*u_r)/12
    sigmastarcoeff_r = sigmastarcoeffTerm1_r+sigmastarcoeffTerm2_r
    Deltasigmastar3_r = sigma3*sigmacoeff_r+sigmastar3*sigmastarcoeff_r
    Deltasigmastar2_r = sigma2*sigmacoeff_r+sigmastar2*sigmastarcoeff_r
    Deltasigmastar1_r = sigma1*sigmacoeff_r+sigmastar1*sigmastarcoeff_r
    Sstar3_r = Deltasigmastar3_r
    Sstar2_r = Deltasigmastar2_r
    Sstar1_r = Deltasigmastar1_r
    S3_r = Sstar3_r
    S2_r = Sstar2_r
    S1_r = Sstar1_r
    Sstardotn_r = Sstar1_r*n1+Sstar2_r*n2+Sstar3_r*n3
    SdotSkerrhat_r = S1_r*Skerrhat1+S2_r*Skerrhat2+S3_r*Skerrhat3
    Sdotn_r = S1_r*n1+S2_r*n2+S3_r*n3
    Sdotv_r = S1_r*v1+S2_r*v2+S3_r*v3
    Sdotxi_r = S1_r*xi1+S2_r*xi2+S3_r*xi3
    HdsumTerm2_r = 6*Sstardotn*Sstardotn_r
    HdsumTerm1_r = 2*Sstar1*Sstar1_r+2*Sstar2*Sstar2_r+2*Sstar3*Sstar3_r
    Hdsum_r = HdsumTerm1_r-HdsumTerm2_r
    Hdcoeff_r = 3*u**2*u_r/2
    Q4_r = 4*eta*prT**4*u*u_r*(-3*eta+4)+8*eta*prT**3*prT_r*u**2*(-3*eta+4)
    gammappsum_r = 2*Deltar*pdotn*pdotn_r/Sigma-Deltar*Sigma_r*pdotn**2/Sigma**2+Deltar_r*pdotn**2/Sigma+2*pdotvr*pdotvr_r/(Sigma*sin2thetaBL)-Sigma_r*pdotvr**2/(Sigma**2*sin2thetaBL)+2*Sigma*pdotxir*pdotxir_r/(Lambt*sin2thetaBL)+Sigma_r*pdotxir**2/(Lambt*sin2thetaBL)-Lambt_r*Sigma*pdotxir**2/(Lambt**2*sin2thetaBL)
    Hnsradicand_r = Q4_r+gammappsum_r
    alpha_r = Lambt*np.sqrt(Deltat*Sigma/Lambt)*(Deltat*Sigma_r/(2*Lambt)-Deltat*Lambt_r*Sigma/(2*Lambt**2)+Deltat_r*Sigma/(2*Lambt))/(Deltat*Sigma)
    betapsum_r = omegatilde*pdotxir_r/Lambt+omegatilde_r*pdotxir/Lambt-Lambt_r*omegatilde*pdotxir/Lambt**2
    HssTerm3_r = Btilde**2*(Sdotn*exp2mu*xisq*(-Q_r-Q_r/(2*np.sqrt(Q)))+Sdotn*exp2mu_r*xisq*(-np.sqrt(Q)-Q)+Sdotn_r*exp2mu*xisq*(-np.sqrt(Q)-Q)+pdotvr*(-Jtilde*Sdotv*pdotn_r-Jtilde*Sdotv_r*pdotn-Jtilde_r*Sdotv*pdotn+Sdotn*pdotvr_r+Sdotn_r*pdotvr)+pdotvr_r*(-Jtilde*Sdotv*pdotn+Sdotn*pdotvr))+Btilde*Btilde_r*(-2*Sdotn*exp2mu*xisq*(np.sqrt(Q)+Q)+2*pdotvr*(-Jtilde*Sdotv*pdotn+Sdotn*pdotvr))+expmu*expnu*pdotxir*(Btilde*Jtilde*Sdotxi*pdotn_r+Btilde*Jtilde*Sdotxi_r*pdotn+Btilde*Jtilde_r*Sdotxi*pdotn+Btilde_r*Jtilde*Sdotxi*pdotn-Sdotn*expmu*expnu*pdotxir_r-Sdotn*expmu*expnu_r*pdotxir-Sdotn*expmu_r*expnu*pdotxir-Sdotn_r*expmu*expnu*pdotxir)+expmu*expnu*pdotxir_r*(Btilde*Jtilde*Sdotxi*pdotn-Sdotn*expmu*expnu*pdotxir)+expmu*expnu_r*pdotxir*(Btilde*Jtilde*Sdotxi*pdotn-Sdotn*expmu*expnu*pdotxir)+expmu_r*expnu*pdotxir*(Btilde*Jtilde*Sdotxi*pdotn-Sdotn*expmu*expnu*pdotxir)
    HssTerm3coeff_r = omegacostheta*(-Q_r-Q_r/(2*np.sqrt(Q)))/(2*Btilde*exp2mu*expmu*expnu*(np.sqrt(Q)+Q)**2)+omegacostheta_r/(Btilde*exp2mu*expmu*expnu*(2*np.sqrt(Q)+2*Q))-expnu_r*omegacostheta/(Btilde*exp2mu*expmu*expnu**2*(2*np.sqrt(Q)+2*Q))-expmu_r*omegacostheta/(Btilde*exp2mu*expmu**2*expnu*(2*np.sqrt(Q)+2*Q))-exp2mu_r*omegacostheta/(Btilde*exp2mu**2*expmu*expnu*(2*np.sqrt(Q)+2*Q))-Btilde_r*omegacostheta/(Btilde**2*exp2mu*expmu*expnu*(2*np.sqrt(Q)+2*Q))
    HssTerm2_r = Btilde**2*xisq*(Jtilde*pdotn*(-Jtilde*Sdotv*pdotn_r-Jtilde*Sdotv_r*pdotn-Jtilde_r*Sdotv*pdotn+Sdotn*pdotvr_r+Sdotn_r*pdotvr)+Jtilde*pdotn_r*(-Jtilde*Sdotv*pdotn+Sdotn*pdotvr)+Jtilde_r*pdotn*(-Jtilde*Sdotv*pdotn+Sdotn*pdotvr)+Sdotv*exp2mu*(Q_r+Q_r/(2*np.sqrt(Q)))+Sdotv*exp2mu_r*(np.sqrt(Q)+Q)+Sdotv_r*exp2mu*(np.sqrt(Q)+Q))+Btilde*Btilde_r*xisq*(2*Jtilde*pdotn*(-Jtilde*Sdotv*pdotn+Sdotn*pdotvr)+2*Sdotv*exp2mu*(np.sqrt(Q)+Q))+expmu*pdotxir*(-Btilde*Sdotxi*expnu*pdotvr_r-Btilde*Sdotxi*expnu_r*pdotvr-Btilde*Sdotxi_r*expnu*pdotvr-Btilde_r*Sdotxi*expnu*pdotvr+Sdotv*exp2nu*expmu*pdotxir_r+Sdotv*exp2nu*expmu_r*pdotxir+Sdotv*exp2nu_r*expmu*pdotxir+Sdotv_r*exp2nu*expmu*pdotxir)+expmu*pdotxir_r*(-Btilde*Sdotxi*expnu*pdotvr+Sdotv*exp2nu*expmu*pdotxir)+expmu_r*pdotxir*(-Btilde*Sdotxi*expnu*pdotvr+Sdotv*exp2nu*expmu*pdotxir)
    HssTerm2coeff_r = Jtilde*omegar*(-Q_r-Q_r/(2*np.sqrt(Q)))/(2*Btilde*exp2mu*expmu*expnu*xisq*(np.sqrt(Q)+Q)**2)+Jtilde*omegar_r/(Btilde*exp2mu*expmu*expnu*xisq*(2*np.sqrt(Q)+2*Q))-Jtilde*expnu_r*omegar/(Btilde*exp2mu*expmu*expnu**2*xisq*(2*np.sqrt(Q)+2*Q))-Jtilde*expmu_r*omegar/(Btilde*exp2mu*expmu**2*expnu*xisq*(2*np.sqrt(Q)+2*Q))-Jtilde*exp2mu_r*omegar/(Btilde*exp2mu**2*expmu*expnu*xisq*(2*np.sqrt(Q)+2*Q))+Jtilde_r*omegar/(Btilde*exp2mu*expmu*expnu*xisq*(2*np.sqrt(Q)+2*Q))-Btilde_r*Jtilde*omegar/(Btilde**2*exp2mu*expmu*expnu*xisq*(2*np.sqrt(Q)+2*Q))
    HssTerm1_r = SdotSkerrhat*omega_r+SdotSkerrhat_r*omega
    Hss_r = HssTerm1_r+HssTerm2*HssTerm2coeff_r+HssTerm2coeff*HssTerm2_r+HssTerm3*HssTerm3coeff_r+HssTerm3coeff*HssTerm3_r
    HsoTerm2c_r = Brtilde*Jtilde*Sdotv*expmu*expnu*pdotxir_r*(np.sqrt(Q)+1)+Brtilde*Jtilde*Sdotv*expmu*expnu_r*pdotxir*(np.sqrt(Q)+1)+Brtilde*Jtilde*Sdotv*expmu_r*expnu*pdotxir*(np.sqrt(Q)+1)+Brtilde*Jtilde*Sdotv_r*expmu*expnu*pdotxir*(np.sqrt(Q)+1)+Brtilde*Jtilde*Q_r*Sdotv*expmu*expnu*pdotxir/(2*np.sqrt(Q))+Brtilde*Jtilde_r*Sdotv*expmu*expnu*pdotxir*(np.sqrt(Q)+1)+Brtilde_r*Jtilde*Sdotv*expmu*expnu*pdotxir*(np.sqrt(Q)+1)
    HsoTerm2b_r = Btilde*expmu*expnu*pdotxir*(2*np.sqrt(Q)+1)*(Jtilde*Sdotv*nur_r+Jtilde*Sdotv_r*nur+Jtilde_r*Sdotv*nur-Sdotn*nucostheta_r*xisq-Sdotn_r*nucostheta*xisq)+Btilde*expmu*expnu*pdotxir_r*(2*np.sqrt(Q)+1)*(Jtilde*Sdotv*nur-Sdotn*nucostheta*xisq)+Btilde*expmu*expnu_r*pdotxir*(2*np.sqrt(Q)+1)*(Jtilde*Sdotv*nur-Sdotn*nucostheta*xisq)+Btilde*expmu_r*expnu*pdotxir*(2*np.sqrt(Q)+1)*(Jtilde*Sdotv*nur-Sdotn*nucostheta*xisq)+Btilde*Q_r*expmu*expnu*pdotxir*(Jtilde*Sdotv*nur-Sdotn*nucostheta*xisq)/np.sqrt(Q)+Btilde_r*expmu*expnu*pdotxir*(2*np.sqrt(Q)+1)*(Jtilde*Sdotv*nur-Sdotn*nucostheta*xisq)
    HsoTerm2a_r = Btilde**2*Jtilde*Sdotxi*(-np.sqrt(Q)*(nur*pdotvr_r+nur_r*pdotvr+pdotn*xisq*(mucostheta_r-nucostheta_r)+pdotn_r*xisq*(mucostheta-nucostheta))-mucostheta*pdotn_r*xisq-mucostheta_r*pdotn*xisq+mur*pdotvr_r*(np.sqrt(Q)+1)+mur_r*pdotvr*(np.sqrt(Q)+1)+Q_r*mur*pdotvr/(2*np.sqrt(Q))+Q_r*(-nur*pdotvr-pdotn*xisq*(mucostheta-nucostheta))/(2*np.sqrt(Q)))+Btilde**2*Jtilde*Sdotxi_r*(np.sqrt(Q)*(-nur*pdotvr-pdotn*xisq*(mucostheta-nucostheta))-mucostheta*pdotn*xisq+mur*pdotvr*(np.sqrt(Q)+1))+Btilde**2*Jtilde_r*Sdotxi*(np.sqrt(Q)*(-nur*pdotvr-pdotn*xisq*(mucostheta-nucostheta))-mucostheta*pdotn*xisq+mur*pdotvr*(np.sqrt(Q)+1))+Btilde*Btilde_r*Jtilde*Sdotxi*(2*np.sqrt(Q)*(-nur*pdotvr-pdotn*xisq*(mucostheta-nucostheta))-2*mucostheta*pdotn*xisq+2*mur*pdotvr*(np.sqrt(Q)+1))
    HsoTerm2_r = HsoTerm2a_r+HsoTerm2b_r-HsoTerm2c_r
    HsoTerm2coeff_r = expnu*(-Q_r-Q_r/(2*np.sqrt(Q)))/(Btilde**2*exp2mu*xisq*(np.sqrt(Q)+Q)**2)+expnu_r/(Btilde**2*exp2mu*xisq*(np.sqrt(Q)+Q))-exp2mu_r*expnu/(Btilde**2*exp2mu**2*xisq*(np.sqrt(Q)+Q))-2*Btilde_r*expnu/(Btilde**3*exp2mu*xisq*(np.sqrt(Q)+Q))
    HsoTerm1_r = SdotSkerrhat*exp2nu*pdotxir*(-Btilde_r+expmu*expnu_r+expmu_r*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq)+SdotSkerrhat*exp2nu*pdotxir_r*(-Btilde+expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq)-SdotSkerrhat*exp2nu*expmu_r*pdotxir*(-Btilde+expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu**2*xisq)+SdotSkerrhat*exp2nu_r*pdotxir*(-Btilde+expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq)+SdotSkerrhat_r*exp2nu*pdotxir*(-Btilde+expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq)-Q_r*SdotSkerrhat*exp2nu*pdotxir*(-Btilde+expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq)-Btilde_r*SdotSkerrhat*exp2nu*pdotxir*(-2*Btilde+2*expmu*expnu)/(Btilde**3*np.sqrt(Q)*expmu*xisq)
    Hso_r = HsoTerm1_r+HsoTerm2*HsoTerm2coeff_r+HsoTerm2coeff*HsoTerm2_r
    Hd_r = Hdcoeff*Hdsum_r+Hdcoeff_r*Hdsum
    Hns_r = np.sqrt(Hnsradicand)*alpha_r+betapsum_r+Hnsradicand_r*alpha/(2*np.sqrt(Hnsradicand))
    Hs_r = Hso_r+Hss_r
    Heff_r = -Hd_r+Hns_r+Hs_r+4*dSS*eta*u**3*u_r*(S1phi**2+S1r**2+S1theta**2+S2phi**2+S2r**2+S2theta**2)
    prTprm_pphi = csi2*n3/(r*sintheta)
    phat3prm_pphi = n3*prTprm_pphi*(1 - 1/csi1) + 1/(r*sintheta)
    phat2prm_pphi = n2*prTprm_pphi*(1 - 1/csi1)
    phat1prm_pphi = n1*prTprm_pphi*(1 - 1/csi1)
    pdotxirprm_pphi = r*(phat1prm_pphi*xi1 + phat2prm_pphi*xi2 + phat3prm_pphi*xi3)
    pdotnprm_pphi = n1*phat1prm_pphi + n2*phat2prm_pphi + n3*phat3prm_pphi
    pdotvrprm_pphi = r*(phat1prm_pphi*v1 + phat2prm_pphi*v2 + phat3prm_pphi*v3)
    DrSipn2prm_pphi = 2*Deltar*pdotn*pdotnprm_pphi/Sigma
    Qprm_pphi = DrSipn2prm_pphi + 2*Qcoeff1*pdotxir*pdotxirprm_pphi + 2*Qcoeff2*pdotvr*pdotvrprm_pphi
    Qminus1prm_pphi = Qprm_pphi
    sigmacoeffTerm2prm_pphi = eta*(eta*r*(-882*DrSipn2prm_pphi + 204*Qminus1prm_pphi + r*(1620*DrSipn2*DrSipn2prm_pphi - 234*DrSipn2*Qminus1prm_pphi - 234*DrSipn2prm_pphi*Qminus1)) + r*(-96*DrSipn2prm_pphi - 436*Qminus1prm_pphi + r*(36*DrSipn2*Qminus1prm_pphi + 36*DrSipn2prm_pphi*Qminus1 - 90*Qminus1*Qminus1prm_pphi)))/(144*r**2)
    sigmacoeffTerm1prm_pphi = eta*(-36*DrSipn2prm_pphi + 3*Qminus1prm_pphi)/12
    sigmacoeffprm_pphi = sigmacoeffTerm1prm_pphi + sigmacoeffTerm2prm_pphi
    sigmastarcoeffTerm2prm_pphi = eta*(eta*r*(-324*DrSipn2prm_pphi + 120*Qminus1prm_pphi + r*(720*DrSipn2*DrSipn2prm_pphi + Qminus1*(-126*DrSipn2prm_pphi - 3*Qminus1prm_pphi) + Qminus1prm_pphi*(-126*DrSipn2 - 3*Qminus1))) + r*(282*DrSipn2prm_pphi + Qminus1*r*(96*DrSipn2prm_pphi - 23*Qminus1prm_pphi) + Qminus1prm_pphi*r*(96*DrSipn2 - 23*Qminus1) - 206*Qminus1prm_pphi))/(72*r**2)
    sigmastarcoeffTerm1prm_pphi = eta*(-30*DrSipn2prm_pphi + 4*Qminus1prm_pphi)/12
    sigmastarcoeffprm_pphi = sigmastarcoeffTerm1prm_pphi + sigmastarcoeffTerm2prm_pphi
    Deltasigmastar3prm_pphi = sigma3*sigmacoeffprm_pphi + sigmastar3*sigmastarcoeffprm_pphi
    Deltasigmastar2prm_pphi = sigma2*sigmacoeffprm_pphi + sigmastar2*sigmastarcoeffprm_pphi
    Deltasigmastar1prm_pphi = sigma1*sigmacoeffprm_pphi + sigmastar1*sigmastarcoeffprm_pphi
    Sstar3prm_pphi = Deltasigmastar3prm_pphi
    Sstar2prm_pphi = Deltasigmastar2prm_pphi
    Sstar1prm_pphi = Deltasigmastar1prm_pphi
    S3prm_pphi = Sstar3prm_pphi
    S2prm_pphi = Sstar2prm_pphi
    S1prm_pphi = Sstar1prm_pphi
    Sstardotnprm_pphi = Sstar1prm_pphi*n1 + Sstar2prm_pphi*n2 + Sstar3prm_pphi*n3
    SdotSkerrhatprm_pphi = S1prm_pphi*Skerrhat1 + S2prm_pphi*Skerrhat2 + S3prm_pphi*Skerrhat3
    Sdotnprm_pphi = S1prm_pphi*n1 + S2prm_pphi*n2 + S3prm_pphi*n3
    Sdotvprm_pphi = S1prm_pphi*v1 + S2prm_pphi*v2 + S3prm_pphi*v3
    Sdotxiprm_pphi = S1prm_pphi*xi1 + S2prm_pphi*xi2 + S3prm_pphi*xi3
    HdsumTerm2prm_pphi = 6*Sstardotn*Sstardotnprm_pphi
    HdsumTerm1prm_pphi = 2*Sstar1*Sstar1prm_pphi + 2*Sstar2*Sstar2prm_pphi + 2*Sstar3*Sstar3prm_pphi
    Hdsumprm_pphi = HdsumTerm1prm_pphi - HdsumTerm2prm_pphi
    Q4prm_pphi = 8*eta*prT**3*prTprm_pphi*u**2*(-3*eta + 4)
    gammappsumprm_pphi = 2*Deltar*pdotn*pdotnprm_pphi/Sigma + 2*pdotvr*pdotvrprm_pphi/(Sigma*sin2thetaBL) + 2*Sigma*pdotxir*pdotxirprm_pphi/(Lambt*sin2thetaBL)
    Hnsradicandprm_pphi = Q4prm_pphi + gammappsumprm_pphi
    betapsumprm_pphi = omegatilde*pdotxirprm_pphi/Lambt
    HssTerm3prm_pphi = Btilde**2*(Sdotn*exp2mu*xisq*(-Qprm_pphi - Qprm_pphi/(2*np.sqrt(Q))) + Sdotnprm_pphi*exp2mu*xisq*(-np.sqrt(Q) - Q) + pdotvr*(-Jtilde*Sdotv*pdotnprm_pphi - Jtilde*Sdotvprm_pphi*pdotn + Sdotn*pdotvrprm_pphi + Sdotnprm_pphi*pdotvr) + pdotvrprm_pphi*(-Jtilde*Sdotv*pdotn + Sdotn*pdotvr)) + expmu*expnu*pdotxir*(Btilde*Jtilde*Sdotxi*pdotnprm_pphi + Btilde*Jtilde*Sdotxiprm_pphi*pdotn - Sdotn*expmu*expnu*pdotxirprm_pphi - Sdotnprm_pphi*expmu*expnu*pdotxir) + expmu*expnu*pdotxirprm_pphi*(Btilde*Jtilde*Sdotxi*pdotn - Sdotn*expmu*expnu*pdotxir)
    HssTerm3coeffprm_pphi = omegacostheta*(-Qprm_pphi - Qprm_pphi/(2*np.sqrt(Q)))/(2*Btilde*exp2mu*expmu*expnu*(np.sqrt(Q) + Q)**2)
    HssTerm2prm_pphi = Btilde**2*xisq*(Jtilde*pdotn*(-Jtilde*Sdotv*pdotnprm_pphi - Jtilde*Sdotvprm_pphi*pdotn + Sdotn*pdotvrprm_pphi + Sdotnprm_pphi*pdotvr) + Jtilde*pdotnprm_pphi*(-Jtilde*Sdotv*pdotn + Sdotn*pdotvr) + Sdotv*exp2mu*(Qprm_pphi + Qprm_pphi/(2*np.sqrt(Q))) + Sdotvprm_pphi*exp2mu*(np.sqrt(Q) + Q)) + expmu*pdotxir*(-Btilde*Sdotxi*expnu*pdotvrprm_pphi - Btilde*Sdotxiprm_pphi*expnu*pdotvr + Sdotv*exp2nu*expmu*pdotxirprm_pphi + Sdotvprm_pphi*exp2nu*expmu*pdotxir) + expmu*pdotxirprm_pphi*(-Btilde*Sdotxi*expnu*pdotvr + Sdotv*exp2nu*expmu*pdotxir)
    HssTerm2coeffprm_pphi = Jtilde*omegar*(-Qprm_pphi - Qprm_pphi/(2*np.sqrt(Q)))/(2*Btilde*exp2mu*expmu*expnu*xisq*(np.sqrt(Q) + Q)**2)
    HssTerm1prm_pphi = SdotSkerrhatprm_pphi*omega
    Hssprm_pphi = HssTerm1prm_pphi + HssTerm2*HssTerm2coeffprm_pphi + HssTerm2coeff*HssTerm2prm_pphi + HssTerm3*HssTerm3coeffprm_pphi + HssTerm3coeff*HssTerm3prm_pphi
    HsoTerm2cprm_pphi = Brtilde*Jtilde*Sdotv*expmu*expnu*pdotxirprm_pphi*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotvprm_pphi*expmu*expnu*pdotxir*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Qprm_pphi*Sdotv*expmu*expnu*pdotxir/(2*np.sqrt(Q))
    HsoTerm2bprm_pphi = Btilde*expmu*expnu*pdotxir*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotvprm_pphi*nur - Sdotnprm_pphi*nucostheta*xisq) + Btilde*expmu*expnu*pdotxirprm_pphi*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq) + Btilde*Qprm_pphi*expmu*expnu*pdotxir*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq)/np.sqrt(Q)
    HsoTerm2aprm_pphi = Btilde**2*Jtilde*Sdotxi*(-np.sqrt(Q)*(nur*pdotvrprm_pphi + pdotnprm_pphi*xisq*(mucostheta - nucostheta)) - mucostheta*pdotnprm_pphi*xisq + mur*pdotvrprm_pphi*(np.sqrt(Q) + 1) + Qprm_pphi*mur*pdotvr/(2*np.sqrt(Q)) + Qprm_pphi*(-nur*pdotvr - pdotn*xisq*(mucostheta - nucostheta))/(2*np.sqrt(Q))) + Btilde**2*Jtilde*Sdotxiprm_pphi*(np.sqrt(Q)*(-nur*pdotvr - pdotn*xisq*(mucostheta - nucostheta)) - mucostheta*pdotn*xisq + mur*pdotvr*(np.sqrt(Q) + 1))
    HsoTerm2prm_pphi = HsoTerm2aprm_pphi + HsoTerm2bprm_pphi - HsoTerm2cprm_pphi
    HsoTerm2coeffprm_pphi = expnu*(-Qprm_pphi - Qprm_pphi/(2*np.sqrt(Q)))/(Btilde**2*exp2mu*xisq*(np.sqrt(Q) + Q)**2)
    HsoTerm1prm_pphi = SdotSkerrhat*exp2nu*pdotxirprm_pphi*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) + SdotSkerrhatprm_pphi*exp2nu*pdotxir*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) - Qprm_pphi*SdotSkerrhat*exp2nu*pdotxir*(-Btilde + expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq)
    Hsoprm_pphi = HsoTerm1prm_pphi + HsoTerm2*HsoTerm2coeffprm_pphi + HsoTerm2coeff*HsoTerm2prm_pphi
    Hdprm_pphi = Hdcoeff*Hdsumprm_pphi
    Hnsprm_pphi = betapsumprm_pphi + Hnsradicandprm_pphi*alpha/(2*np.sqrt(Hnsradicand))
    Hsprm_pphi = Hsoprm_pphi + Hssprm_pphi
    Heffprm_pphi = -Hdprm_pphi + Hnsprm_pphi + Hsprm_pphi
    prT_rprm_pphi = -csi2*n3/(r**2*sintheta) + csi2_r*n3/(r*sintheta)
    phat3_rprm_pphi = n3*prT_rprm_pphi*(1 - 1/csi1) - 1/(r**2*sintheta) + csi1_r*n3*prTprm_pphi/csi1**2
    phat2_rprm_pphi = n2*prT_rprm_pphi*(1 - 1/csi1) + csi1_r*n2*prTprm_pphi/csi1**2
    phat1_rprm_pphi = n1*prT_rprm_pphi*(1 - 1/csi1) + csi1_r*n1*prTprm_pphi/csi1**2
    pdotxir_rprm_pphi = phat1prm_pphi*xi1 + phat2prm_pphi*xi2 + phat3prm_pphi*xi3 + r*(phat1_rprm_pphi*xi1 + phat2_rprm_pphi*xi2 + phat3_rprm_pphi*xi3)
    pdotn_rprm_pphi = n1*phat1_rprm_pphi + n2*phat2_rprm_pphi + n3*phat3_rprm_pphi
    pdotvr_rprm_pphi = phat1prm_pphi*v1 + phat2prm_pphi*v2 + phat3prm_pphi*v3 + r*(phat1_rprm_pphi*v1 + phat2_rprm_pphi*v2 + phat3_rprm_pphi*v3)
    DrSipn2_rprm_pphi = 2*Deltar*pdotn*pdotn_rprm_pphi/Sigma + 2*Deltar*pdotn_r*pdotnprm_pphi/Sigma - 2*Deltar*Sigma_r*pdotn*pdotnprm_pphi/Sigma**2 + 2*Deltar_r*pdotn*pdotnprm_pphi/Sigma
    Q_rprm_pphi = DrSipn2_rprm_pphi + 2*Qcoeff1*pdotxir*pdotxir_rprm_pphi + 2*Qcoeff1*pdotxir_r*pdotxirprm_pphi + 2*Qcoeff1_r*pdotxir*pdotxirprm_pphi + 2*Qcoeff2*pdotvr*pdotvr_rprm_pphi + 2*Qcoeff2*pdotvr_r*pdotvrprm_pphi + 2*Qcoeff2_r*pdotvr*pdotvrprm_pphi
    Qminus1_rprm_pphi = Q_rprm_pphi
    sigmacoeffTerm2_rprm_pphi = eta*(-96*DrSipn2prm_pphi - 436*Qminus1prm_pphi + eta*(-882*DrSipn2prm_pphi + 204*Qminus1prm_pphi + r*(1620*DrSipn2*DrSipn2prm_pphi - 234*DrSipn2*Qminus1prm_pphi - 234*DrSipn2prm_pphi*Qminus1) + r*(1620*DrSipn2*DrSipn2prm_pphi - 234*DrSipn2*Qminus1prm_pphi - 882*DrSipn2_rprm_pphi - 234*DrSipn2prm_pphi*Qminus1 + 204*Qminus1_rprm_pphi + r*(1620*DrSipn2*DrSipn2_rprm_pphi - 234*DrSipn2*Qminus1_rprm_pphi + 1620*DrSipn2_r*DrSipn2prm_pphi - 234*DrSipn2_r*Qminus1prm_pphi - 234*DrSipn2_rprm_pphi*Qminus1 - 234*DrSipn2prm_pphi*Qminus1_r))) + r*(36*DrSipn2*Qminus1prm_pphi + 36*DrSipn2prm_pphi*Qminus1 - 90*Qminus1*Qminus1prm_pphi) + r*(36*DrSipn2*Qminus1prm_pphi - 96*DrSipn2_rprm_pphi + 36*DrSipn2prm_pphi*Qminus1 - 90*Qminus1*Qminus1prm_pphi - 436*Qminus1_rprm_pphi + r*(36*DrSipn2*Qminus1_rprm_pphi + 36*DrSipn2_r*Qminus1prm_pphi + 36*DrSipn2_rprm_pphi*Qminus1 + 36*DrSipn2prm_pphi*Qminus1_r - 90*Qminus1*Qminus1_rprm_pphi - 90*Qminus1_r*Qminus1prm_pphi)))/(144*r**2) - eta*(eta*r*(-882*DrSipn2prm_pphi + 204*Qminus1prm_pphi + r*(1620*DrSipn2*DrSipn2prm_pphi - 234*DrSipn2*Qminus1prm_pphi - 234*DrSipn2prm_pphi*Qminus1)) + r*(-96*DrSipn2prm_pphi - 436*Qminus1prm_pphi + r*(36*DrSipn2*Qminus1prm_pphi + 36*DrSipn2prm_pphi*Qminus1 - 90*Qminus1*Qminus1prm_pphi)))/(72*r**3)
    sigmacoeffTerm1_rprm_pphi = eta*(-36*DrSipn2_rprm_pphi + 3*Qminus1_rprm_pphi)/12
    sigmacoeff_rprm_pphi = sigmacoeffTerm1_rprm_pphi + sigmacoeffTerm2_rprm_pphi
    sigmastarcoeffTerm2_rprm_pphi = eta*(282*DrSipn2prm_pphi + Qminus1*r*(96*DrSipn2prm_pphi - 23*Qminus1prm_pphi) + Qminus1prm_pphi*r*(96*DrSipn2 - 23*Qminus1) - 206*Qminus1prm_pphi + eta*(-324*DrSipn2prm_pphi + 120*Qminus1prm_pphi + r*(720*DrSipn2*DrSipn2prm_pphi + Qminus1*(-126*DrSipn2prm_pphi - 3*Qminus1prm_pphi) + Qminus1prm_pphi*(-126*DrSipn2 - 3*Qminus1)) + r*(720*DrSipn2*DrSipn2prm_pphi - 324*DrSipn2_rprm_pphi + Qminus1*(-126*DrSipn2prm_pphi - 3*Qminus1prm_pphi) + 120*Qminus1_rprm_pphi + Qminus1prm_pphi*(-126*DrSipn2 - 3*Qminus1) + r*(720*DrSipn2*DrSipn2_rprm_pphi + 720*DrSipn2_r*DrSipn2prm_pphi + Qminus1*(-126*DrSipn2_rprm_pphi - 3*Qminus1_rprm_pphi) + Qminus1_r*(-126*DrSipn2prm_pphi - 3*Qminus1prm_pphi) + Qminus1_rprm_pphi*(-126*DrSipn2 - 3*Qminus1) + Qminus1prm_pphi*(-126*DrSipn2_r - 3*Qminus1_r)))) + r*(282*DrSipn2_rprm_pphi + Qminus1*r*(96*DrSipn2_rprm_pphi - 23*Qminus1_rprm_pphi) + Qminus1*(96*DrSipn2prm_pphi - 23*Qminus1prm_pphi) + Qminus1_r*r*(96*DrSipn2prm_pphi - 23*Qminus1prm_pphi) + Qminus1_rprm_pphi*r*(96*DrSipn2 - 23*Qminus1) - 206*Qminus1_rprm_pphi + Qminus1prm_pphi*r*(96*DrSipn2_r - 23*Qminus1_r) + Qminus1prm_pphi*(96*DrSipn2 - 23*Qminus1)))/(72*r**2) - eta*(eta*r*(-324*DrSipn2prm_pphi + 120*Qminus1prm_pphi + r*(720*DrSipn2*DrSipn2prm_pphi + Qminus1*(-126*DrSipn2prm_pphi - 3*Qminus1prm_pphi) + Qminus1prm_pphi*(-126*DrSipn2 - 3*Qminus1))) + r*(282*DrSipn2prm_pphi + Qminus1*r*(96*DrSipn2prm_pphi - 23*Qminus1prm_pphi) + Qminus1prm_pphi*r*(96*DrSipn2 - 23*Qminus1) - 206*Qminus1prm_pphi))/(36*r**3)
    sigmastarcoeffTerm1_rprm_pphi = eta*(-30*DrSipn2_rprm_pphi + 4*Qminus1_rprm_pphi)/12
    sigmastarcoeff_rprm_pphi = sigmastarcoeffTerm1_rprm_pphi + sigmastarcoeffTerm2_rprm_pphi
    Deltasigmastar3_rprm_pphi = sigma3*sigmacoeff_rprm_pphi + sigmastar3*sigmastarcoeff_rprm_pphi
    Deltasigmastar2_rprm_pphi = sigma2*sigmacoeff_rprm_pphi + sigmastar2*sigmastarcoeff_rprm_pphi
    Deltasigmastar1_rprm_pphi = sigma1*sigmacoeff_rprm_pphi + sigmastar1*sigmastarcoeff_rprm_pphi
    Sstar3_rprm_pphi = Deltasigmastar3_rprm_pphi
    Sstar2_rprm_pphi = Deltasigmastar2_rprm_pphi
    Sstar1_rprm_pphi = Deltasigmastar1_rprm_pphi
    S3_rprm_pphi = Sstar3_rprm_pphi
    S2_rprm_pphi = Sstar2_rprm_pphi
    S1_rprm_pphi = Sstar1_rprm_pphi
    Sstardotn_rprm_pphi = Sstar1_rprm_pphi*n1 + Sstar2_rprm_pphi*n2 + Sstar3_rprm_pphi*n3
    SdotSkerrhat_rprm_pphi = S1_rprm_pphi*Skerrhat1 + S2_rprm_pphi*Skerrhat2 + S3_rprm_pphi*Skerrhat3
    Sdotn_rprm_pphi = S1_rprm_pphi*n1 + S2_rprm_pphi*n2 + S3_rprm_pphi*n3
    Sdotv_rprm_pphi = S1_rprm_pphi*v1 + S2_rprm_pphi*v2 + S3_rprm_pphi*v3
    Sdotxi_rprm_pphi = S1_rprm_pphi*xi1 + S2_rprm_pphi*xi2 + S3_rprm_pphi*xi3
    HdsumTerm2_rprm_pphi = 6*Sstardotn*Sstardotn_rprm_pphi + 6*Sstardotn_r*Sstardotnprm_pphi
    HdsumTerm1_rprm_pphi = 2*Sstar1*Sstar1_rprm_pphi + 2*Sstar1_r*Sstar1prm_pphi + 2*Sstar2*Sstar2_rprm_pphi + 2*Sstar2_r*Sstar2prm_pphi + 2*Sstar3*Sstar3_rprm_pphi + 2*Sstar3_r*Sstar3prm_pphi
    Hdsum_rprm_pphi = HdsumTerm1_rprm_pphi - HdsumTerm2_rprm_pphi
    Q4_rprm_pphi = 8*eta*prT**3*prT_rprm_pphi*u**2*(-3*eta + 4) + 16*eta*prT**3*prTprm_pphi*u*u_r*(-3*eta + 4) + 24*eta*prT**2*prT_r*prTprm_pphi*u**2*(-3*eta + 4)
    gammappsum_rprm_pphi = 2*Deltar*pdotn*pdotn_rprm_pphi/Sigma + 2*Deltar*pdotn_r*pdotnprm_pphi/Sigma - 2*Deltar*Sigma_r*pdotn*pdotnprm_pphi/Sigma**2 + 2*Deltar_r*pdotn*pdotnprm_pphi/Sigma + 2*pdotvr*pdotvr_rprm_pphi/(Sigma*sin2thetaBL) + 2*pdotvr_r*pdotvrprm_pphi/(Sigma*sin2thetaBL) - 2*Sigma_r*pdotvr*pdotvrprm_pphi/(Sigma**2*sin2thetaBL) + 2*Sigma*pdotxir*pdotxir_rprm_pphi/(Lambt*sin2thetaBL) + 2*Sigma*pdotxir_r*pdotxirprm_pphi/(Lambt*sin2thetaBL) + 2*Sigma_r*pdotxir*pdotxirprm_pphi/(Lambt*sin2thetaBL) - 2*Lambt_r*Sigma*pdotxir*pdotxirprm_pphi/(Lambt**2*sin2thetaBL)
    Hnsradicand_rprm_pphi = Q4_rprm_pphi + gammappsum_rprm_pphi
    betapsum_rprm_pphi = omegatilde*pdotxir_rprm_pphi/Lambt + omegatilde_r*pdotxirprm_pphi/Lambt - Lambt_r*omegatilde*pdotxirprm_pphi/Lambt**2
    HssTerm3_rprm_pphi = Btilde**2*(Sdotn*exp2mu*xisq*(-Q_rprm_pphi - Q_rprm_pphi/(2*np.sqrt(Q)) + Q_r*Qprm_pphi/(4*Q**(3/2))) + Sdotn*exp2mu_r*xisq*(-Qprm_pphi - Qprm_pphi/(2*np.sqrt(Q))) + Sdotn_r*exp2mu*xisq*(-Qprm_pphi - Qprm_pphi/(2*np.sqrt(Q))) + Sdotn_rprm_pphi*exp2mu*xisq*(-np.sqrt(Q) - Q) + Sdotnprm_pphi*exp2mu*xisq*(-Q_r - Q_r/(2*np.sqrt(Q))) + Sdotnprm_pphi*exp2mu_r*xisq*(-np.sqrt(Q) - Q) + pdotvr*(-Jtilde*Sdotv*pdotn_rprm_pphi - Jtilde*Sdotv_r*pdotnprm_pphi - Jtilde*Sdotv_rprm_pphi*pdotn - Jtilde*Sdotvprm_pphi*pdotn_r - Jtilde_r*Sdotv*pdotnprm_pphi - Jtilde_r*Sdotvprm_pphi*pdotn + Sdotn*pdotvr_rprm_pphi + Sdotn_r*pdotvrprm_pphi + Sdotn_rprm_pphi*pdotvr + Sdotnprm_pphi*pdotvr_r) + pdotvr_r*(-Jtilde*Sdotv*pdotnprm_pphi - Jtilde*Sdotvprm_pphi*pdotn + Sdotn*pdotvrprm_pphi + Sdotnprm_pphi*pdotvr) + pdotvr_rprm_pphi*(-Jtilde*Sdotv*pdotn + Sdotn*pdotvr) + pdotvrprm_pphi*(-Jtilde*Sdotv*pdotn_r - Jtilde*Sdotv_r*pdotn - Jtilde_r*Sdotv*pdotn + Sdotn*pdotvr_r + Sdotn_r*pdotvr)) + Btilde*Btilde_r*(Sdotn*exp2mu*xisq*(-2*Qprm_pphi - Qprm_pphi/np.sqrt(Q)) + Sdotnprm_pphi*exp2mu*xisq*(-2*np.sqrt(Q) - 2*Q) + pdotvr*(-2*Jtilde*Sdotv*pdotnprm_pphi - 2*Jtilde*Sdotvprm_pphi*pdotn + 2*Sdotn*pdotvrprm_pphi + 2*Sdotnprm_pphi*pdotvr) + pdotvrprm_pphi*(-2*Jtilde*Sdotv*pdotn + 2*Sdotn*pdotvr)) + expmu*expnu*pdotxir*(Btilde*Jtilde*Sdotxi*pdotn_rprm_pphi + Btilde*Jtilde*Sdotxi_r*pdotnprm_pphi + Btilde*Jtilde*Sdotxi_rprm_pphi*pdotn + Btilde*Jtilde*Sdotxiprm_pphi*pdotn_r + Btilde*Jtilde_r*Sdotxi*pdotnprm_pphi + Btilde*Jtilde_r*Sdotxiprm_pphi*pdotn + Btilde_r*Jtilde*Sdotxi*pdotnprm_pphi + Btilde_r*Jtilde*Sdotxiprm_pphi*pdotn - Sdotn*expmu*expnu*pdotxir_rprm_pphi - Sdotn*expmu*expnu_r*pdotxirprm_pphi - Sdotn*expmu_r*expnu*pdotxirprm_pphi - Sdotn_r*expmu*expnu*pdotxirprm_pphi - Sdotn_rprm_pphi*expmu*expnu*pdotxir - Sdotnprm_pphi*expmu*expnu*pdotxir_r - Sdotnprm_pphi*expmu*expnu_r*pdotxir - Sdotnprm_pphi*expmu_r*expnu*pdotxir) + expmu*expnu*pdotxir_r*(Btilde*Jtilde*Sdotxi*pdotnprm_pphi + Btilde*Jtilde*Sdotxiprm_pphi*pdotn - Sdotn*expmu*expnu*pdotxirprm_pphi - Sdotnprm_pphi*expmu*expnu*pdotxir) + expmu*expnu*pdotxir_rprm_pphi*(Btilde*Jtilde*Sdotxi*pdotn - Sdotn*expmu*expnu*pdotxir) + expmu*expnu*pdotxirprm_pphi*(Btilde*Jtilde*Sdotxi*pdotn_r + Btilde*Jtilde*Sdotxi_r*pdotn + Btilde*Jtilde_r*Sdotxi*pdotn + Btilde_r*Jtilde*Sdotxi*pdotn - Sdotn*expmu*expnu*pdotxir_r - Sdotn*expmu*expnu_r*pdotxir - Sdotn*expmu_r*expnu*pdotxir - Sdotn_r*expmu*expnu*pdotxir) + expmu*expnu_r*pdotxir*(Btilde*Jtilde*Sdotxi*pdotnprm_pphi + Btilde*Jtilde*Sdotxiprm_pphi*pdotn - Sdotn*expmu*expnu*pdotxirprm_pphi - Sdotnprm_pphi*expmu*expnu*pdotxir) + expmu*expnu_r*pdotxirprm_pphi*(Btilde*Jtilde*Sdotxi*pdotn - Sdotn*expmu*expnu*pdotxir) + expmu_r*expnu*pdotxir*(Btilde*Jtilde*Sdotxi*pdotnprm_pphi + Btilde*Jtilde*Sdotxiprm_pphi*pdotn - Sdotn*expmu*expnu*pdotxirprm_pphi - Sdotnprm_pphi*expmu*expnu*pdotxir) + expmu_r*expnu*pdotxirprm_pphi*(Btilde*Jtilde*Sdotxi*pdotn - Sdotn*expmu*expnu*pdotxir)
    HssTerm3coeff_rprm_pphi = omegacostheta*(-Q_rprm_pphi - Q_rprm_pphi/(2*np.sqrt(Q)) + Q_r*Qprm_pphi/(4*Q**(3/2)))/(2*Btilde*exp2mu*expmu*expnu*(np.sqrt(Q) + Q)**2) + omegacostheta*(-Q_r - Q_r/(2*np.sqrt(Q)))*(-2*Qprm_pphi - Qprm_pphi/np.sqrt(Q))/(2*Btilde*exp2mu*expmu*expnu*(np.sqrt(Q) + Q)**3) + omegacostheta_r*(-2*Qprm_pphi - Qprm_pphi/np.sqrt(Q))/(Btilde*exp2mu*expmu*expnu*(2*np.sqrt(Q) + 2*Q)**2) - expnu_r*omegacostheta*(-2*Qprm_pphi - Qprm_pphi/np.sqrt(Q))/(Btilde*exp2mu*expmu*expnu**2*(2*np.sqrt(Q) + 2*Q)**2) - expmu_r*omegacostheta*(-2*Qprm_pphi - Qprm_pphi/np.sqrt(Q))/(Btilde*exp2mu*expmu**2*expnu*(2*np.sqrt(Q) + 2*Q)**2) - exp2mu_r*omegacostheta*(-2*Qprm_pphi - Qprm_pphi/np.sqrt(Q))/(Btilde*exp2mu**2*expmu*expnu*(2*np.sqrt(Q) + 2*Q)**2) - Btilde_r*omegacostheta*(-2*Qprm_pphi - Qprm_pphi/np.sqrt(Q))/(Btilde**2*exp2mu*expmu*expnu*(2*np.sqrt(Q) + 2*Q)**2)
    HssTerm2_rprm_pphi = Btilde**2*xisq*(Jtilde*pdotn*(-Jtilde*Sdotv*pdotn_rprm_pphi - Jtilde*Sdotv_r*pdotnprm_pphi - Jtilde*Sdotv_rprm_pphi*pdotn - Jtilde*Sdotvprm_pphi*pdotn_r - Jtilde_r*Sdotv*pdotnprm_pphi - Jtilde_r*Sdotvprm_pphi*pdotn + Sdotn*pdotvr_rprm_pphi + Sdotn_r*pdotvrprm_pphi + Sdotn_rprm_pphi*pdotvr + Sdotnprm_pphi*pdotvr_r) + Jtilde*pdotn_r*(-Jtilde*Sdotv*pdotnprm_pphi - Jtilde*Sdotvprm_pphi*pdotn + Sdotn*pdotvrprm_pphi + Sdotnprm_pphi*pdotvr) + Jtilde*pdotn_rprm_pphi*(-Jtilde*Sdotv*pdotn + Sdotn*pdotvr) + Jtilde*pdotnprm_pphi*(-Jtilde*Sdotv*pdotn_r - Jtilde*Sdotv_r*pdotn - Jtilde_r*Sdotv*pdotn + Sdotn*pdotvr_r + Sdotn_r*pdotvr) + Jtilde_r*pdotn*(-Jtilde*Sdotv*pdotnprm_pphi - Jtilde*Sdotvprm_pphi*pdotn + Sdotn*pdotvrprm_pphi + Sdotnprm_pphi*pdotvr) + Jtilde_r*pdotnprm_pphi*(-Jtilde*Sdotv*pdotn + Sdotn*pdotvr) + Sdotv*exp2mu*(Q_rprm_pphi + Q_rprm_pphi/(2*np.sqrt(Q)) - Q_r*Qprm_pphi/(4*Q**(3/2))) + Sdotv*exp2mu_r*(Qprm_pphi + Qprm_pphi/(2*np.sqrt(Q))) + Sdotv_r*exp2mu*(Qprm_pphi + Qprm_pphi/(2*np.sqrt(Q))) + Sdotv_rprm_pphi*exp2mu*(np.sqrt(Q) + Q) + Sdotvprm_pphi*exp2mu*(Q_r + Q_r/(2*np.sqrt(Q))) + Sdotvprm_pphi*exp2mu_r*(np.sqrt(Q) + Q)) + Btilde*Btilde_r*xisq*(Jtilde*pdotn*(-2*Jtilde*Sdotv*pdotnprm_pphi - 2*Jtilde*Sdotvprm_pphi*pdotn + 2*Sdotn*pdotvrprm_pphi + 2*Sdotnprm_pphi*pdotvr) + Jtilde*pdotnprm_pphi*(-2*Jtilde*Sdotv*pdotn + 2*Sdotn*pdotvr) + Sdotv*exp2mu*(2*Qprm_pphi + Qprm_pphi/np.sqrt(Q)) + Sdotvprm_pphi*exp2mu*(2*np.sqrt(Q) + 2*Q)) + expmu*pdotxir*(-Btilde*Sdotxi*expnu*pdotvr_rprm_pphi - Btilde*Sdotxi*expnu_r*pdotvrprm_pphi - Btilde*Sdotxi_r*expnu*pdotvrprm_pphi - Btilde*Sdotxi_rprm_pphi*expnu*pdotvr - Btilde*Sdotxiprm_pphi*expnu*pdotvr_r - Btilde*Sdotxiprm_pphi*expnu_r*pdotvr - Btilde_r*Sdotxi*expnu*pdotvrprm_pphi - Btilde_r*Sdotxiprm_pphi*expnu*pdotvr + Sdotv*exp2nu*expmu*pdotxir_rprm_pphi + Sdotv*exp2nu*expmu_r*pdotxirprm_pphi + Sdotv*exp2nu_r*expmu*pdotxirprm_pphi + Sdotv_r*exp2nu*expmu*pdotxirprm_pphi + Sdotv_rprm_pphi*exp2nu*expmu*pdotxir + Sdotvprm_pphi*exp2nu*expmu*pdotxir_r + Sdotvprm_pphi*exp2nu*expmu_r*pdotxir + Sdotvprm_pphi*exp2nu_r*expmu*pdotxir) + expmu*pdotxir_r*(-Btilde*Sdotxi*expnu*pdotvrprm_pphi - Btilde*Sdotxiprm_pphi*expnu*pdotvr + Sdotv*exp2nu*expmu*pdotxirprm_pphi + Sdotvprm_pphi*exp2nu*expmu*pdotxir) + expmu*pdotxir_rprm_pphi*(-Btilde*Sdotxi*expnu*pdotvr + Sdotv*exp2nu*expmu*pdotxir) + expmu*pdotxirprm_pphi*(-Btilde*Sdotxi*expnu*pdotvr_r - Btilde*Sdotxi*expnu_r*pdotvr - Btilde*Sdotxi_r*expnu*pdotvr - Btilde_r*Sdotxi*expnu*pdotvr + Sdotv*exp2nu*expmu*pdotxir_r + Sdotv*exp2nu*expmu_r*pdotxir + Sdotv*exp2nu_r*expmu*pdotxir + Sdotv_r*exp2nu*expmu*pdotxir) + expmu_r*pdotxir*(-Btilde*Sdotxi*expnu*pdotvrprm_pphi - Btilde*Sdotxiprm_pphi*expnu*pdotvr + Sdotv*exp2nu*expmu*pdotxirprm_pphi + Sdotvprm_pphi*exp2nu*expmu*pdotxir) + expmu_r*pdotxirprm_pphi*(-Btilde*Sdotxi*expnu*pdotvr + Sdotv*exp2nu*expmu*pdotxir)
    HssTerm2coeff_rprm_pphi = Jtilde*omegar*(-Q_rprm_pphi - Q_rprm_pphi/(2*np.sqrt(Q)) + Q_r*Qprm_pphi/(4*Q**(3/2)))/(2*Btilde*exp2mu*expmu*expnu*xisq*(np.sqrt(Q) + Q)**2) + Jtilde*omegar*(-Q_r - Q_r/(2*np.sqrt(Q)))*(-2*Qprm_pphi - Qprm_pphi/np.sqrt(Q))/(2*Btilde*exp2mu*expmu*expnu*xisq*(np.sqrt(Q) + Q)**3) + Jtilde*omegar_r*(-2*Qprm_pphi - Qprm_pphi/np.sqrt(Q))/(Btilde*exp2mu*expmu*expnu*xisq*(2*np.sqrt(Q) + 2*Q)**2) - Jtilde*expnu_r*omegar*(-2*Qprm_pphi - Qprm_pphi/np.sqrt(Q))/(Btilde*exp2mu*expmu*expnu**2*xisq*(2*np.sqrt(Q) + 2*Q)**2) - Jtilde*expmu_r*omegar*(-2*Qprm_pphi - Qprm_pphi/np.sqrt(Q))/(Btilde*exp2mu*expmu**2*expnu*xisq*(2*np.sqrt(Q) + 2*Q)**2) - Jtilde*exp2mu_r*omegar*(-2*Qprm_pphi - Qprm_pphi/np.sqrt(Q))/(Btilde*exp2mu**2*expmu*expnu*xisq*(2*np.sqrt(Q) + 2*Q)**2) + Jtilde_r*omegar*(-2*Qprm_pphi - Qprm_pphi/np.sqrt(Q))/(Btilde*exp2mu*expmu*expnu*xisq*(2*np.sqrt(Q) + 2*Q)**2) - Btilde_r*Jtilde*omegar*(-2*Qprm_pphi - Qprm_pphi/np.sqrt(Q))/(Btilde**2*exp2mu*expmu*expnu*xisq*(2*np.sqrt(Q) + 2*Q)**2)
    HssTerm1_rprm_pphi = SdotSkerrhat_rprm_pphi*omega + SdotSkerrhatprm_pphi*omega_r
    Hss_rprm_pphi = HssTerm1_rprm_pphi + HssTerm2*HssTerm2coeff_rprm_pphi + HssTerm2_r*HssTerm2coeffprm_pphi + HssTerm2_rprm_pphi*HssTerm2coeff + HssTerm2coeff_r*HssTerm2prm_pphi + HssTerm3*HssTerm3coeff_rprm_pphi + HssTerm3_r*HssTerm3coeffprm_pphi + HssTerm3_rprm_pphi*HssTerm3coeff + HssTerm3coeff_r*HssTerm3prm_pphi
    HsoTerm2c_rprm_pphi = Brtilde*Jtilde*Sdotv*expmu*expnu*pdotxir_rprm_pphi*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotv*expmu*expnu_r*pdotxirprm_pphi*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotv*expmu_r*expnu*pdotxirprm_pphi*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotv_r*expmu*expnu*pdotxirprm_pphi*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotv_rprm_pphi*expmu*expnu*pdotxir*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotvprm_pphi*expmu*expnu*pdotxir_r*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotvprm_pphi*expmu*expnu_r*pdotxir*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Sdotvprm_pphi*expmu_r*expnu*pdotxir*(np.sqrt(Q) + 1) + Brtilde*Jtilde*Q_r*Sdotv*expmu*expnu*pdotxirprm_pphi/(2*np.sqrt(Q)) + Brtilde*Jtilde*Q_r*Sdotvprm_pphi*expmu*expnu*pdotxir/(2*np.sqrt(Q)) + Brtilde*Jtilde*Q_rprm_pphi*Sdotv*expmu*expnu*pdotxir/(2*np.sqrt(Q)) + Brtilde*Jtilde*Qprm_pphi*Sdotv*expmu*expnu*pdotxir_r/(2*np.sqrt(Q)) + Brtilde*Jtilde*Qprm_pphi*Sdotv*expmu*expnu_r*pdotxir/(2*np.sqrt(Q)) + Brtilde*Jtilde*Qprm_pphi*Sdotv*expmu_r*expnu*pdotxir/(2*np.sqrt(Q)) + Brtilde*Jtilde*Qprm_pphi*Sdotv_r*expmu*expnu*pdotxir/(2*np.sqrt(Q)) - Brtilde*Jtilde*Q_r*Qprm_pphi*Sdotv*expmu*expnu*pdotxir/(4*Q**(3/2)) + Brtilde*Jtilde_r*Sdotv*expmu*expnu*pdotxirprm_pphi*(np.sqrt(Q) + 1) + Brtilde*Jtilde_r*Sdotvprm_pphi*expmu*expnu*pdotxir*(np.sqrt(Q) + 1) + Brtilde*Jtilde_r*Qprm_pphi*Sdotv*expmu*expnu*pdotxir/(2*np.sqrt(Q)) + Brtilde_r*Jtilde*Sdotv*expmu*expnu*pdotxirprm_pphi*(np.sqrt(Q) + 1) + Brtilde_r*Jtilde*Sdotvprm_pphi*expmu*expnu*pdotxir*(np.sqrt(Q) + 1) + Brtilde_r*Jtilde*Qprm_pphi*Sdotv*expmu*expnu*pdotxir/(2*np.sqrt(Q))
    HsoTerm2b_rprm_pphi = Btilde*expmu*expnu*pdotxir*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv_rprm_pphi*nur + Jtilde*Sdotvprm_pphi*nur_r + Jtilde_r*Sdotvprm_pphi*nur - Sdotn_rprm_pphi*nucostheta*xisq - Sdotnprm_pphi*nucostheta_r*xisq) + Btilde*expmu*expnu*pdotxir_r*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotvprm_pphi*nur - Sdotnprm_pphi*nucostheta*xisq) + Btilde*expmu*expnu*pdotxir_rprm_pphi*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq) + Btilde*expmu*expnu*pdotxirprm_pphi*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv*nur_r + Jtilde*Sdotv_r*nur + Jtilde_r*Sdotv*nur - Sdotn*nucostheta_r*xisq - Sdotn_r*nucostheta*xisq) + Btilde*expmu*expnu_r*pdotxir*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotvprm_pphi*nur - Sdotnprm_pphi*nucostheta*xisq) + Btilde*expmu*expnu_r*pdotxirprm_pphi*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq) + Btilde*expmu_r*expnu*pdotxir*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotvprm_pphi*nur - Sdotnprm_pphi*nucostheta*xisq) + Btilde*expmu_r*expnu*pdotxirprm_pphi*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq) + Btilde*Q_r*expmu*expnu*pdotxir*(Jtilde*Sdotvprm_pphi*nur - Sdotnprm_pphi*nucostheta*xisq)/np.sqrt(Q) + Btilde*Q_r*expmu*expnu*pdotxirprm_pphi*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq)/np.sqrt(Q) + Btilde*Q_rprm_pphi*expmu*expnu*pdotxir*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq)/np.sqrt(Q) + Btilde*Qprm_pphi*expmu*expnu*pdotxir*(Jtilde*Sdotv*nur_r + Jtilde*Sdotv_r*nur + Jtilde_r*Sdotv*nur - Sdotn*nucostheta_r*xisq - Sdotn_r*nucostheta*xisq)/np.sqrt(Q) + Btilde*Qprm_pphi*expmu*expnu*pdotxir_r*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq)/np.sqrt(Q) + Btilde*Qprm_pphi*expmu*expnu_r*pdotxir*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq)/np.sqrt(Q) + Btilde*Qprm_pphi*expmu_r*expnu*pdotxir*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq)/np.sqrt(Q) - Btilde*Q_r*Qprm_pphi*expmu*expnu*pdotxir*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq)/(2*Q**(3/2)) + Btilde_r*expmu*expnu*pdotxir*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotvprm_pphi*nur - Sdotnprm_pphi*nucostheta*xisq) + Btilde_r*expmu*expnu*pdotxirprm_pphi*(2*np.sqrt(Q) + 1)*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq) + Btilde_r*Qprm_pphi*expmu*expnu*pdotxir*(Jtilde*Sdotv*nur - Sdotn*nucostheta*xisq)/np.sqrt(Q)
    HsoTerm2a_rprm_pphi = Btilde**2*Jtilde*Sdotxi*(-np.sqrt(Q)*(nur*pdotvr_rprm_pphi + nur_r*pdotvrprm_pphi + pdotn_rprm_pphi*xisq*(mucostheta - nucostheta) + pdotnprm_pphi*xisq*(mucostheta_r - nucostheta_r)) - mucostheta*pdotn_rprm_pphi*xisq - mucostheta_r*pdotnprm_pphi*xisq + mur*pdotvr_rprm_pphi*(np.sqrt(Q) + 1) + mur_r*pdotvrprm_pphi*(np.sqrt(Q) + 1) + Q_r*mur*pdotvrprm_pphi/(2*np.sqrt(Q)) + Q_r*(-nur*pdotvrprm_pphi + pdotnprm_pphi*xisq*(-mucostheta + nucostheta))/(2*np.sqrt(Q)) + Q_rprm_pphi*mur*pdotvr/(2*np.sqrt(Q)) + Q_rprm_pphi*(-nur*pdotvr + pdotn*xisq*(-mucostheta + nucostheta))/(2*np.sqrt(Q)) + Qprm_pphi*mur*pdotvr_r/(2*np.sqrt(Q)) + Qprm_pphi*mur_r*pdotvr/(2*np.sqrt(Q)) - Qprm_pphi*(nur*pdotvr_r + nur_r*pdotvr + pdotn*xisq*(mucostheta_r - nucostheta_r) + pdotn_r*xisq*(mucostheta - nucostheta))/(2*np.sqrt(Q)) - Q_r*Qprm_pphi*mur*pdotvr/(4*Q**(3/2)) - Q_r*Qprm_pphi*(-nur*pdotvr + pdotn*xisq*(-mucostheta + nucostheta))/(4*Q**(3/2))) + Btilde**2*Jtilde*Sdotxi_r*(np.sqrt(Q)*(-nur*pdotvrprm_pphi + pdotnprm_pphi*xisq*(-mucostheta + nucostheta)) - mucostheta*pdotnprm_pphi*xisq + mur*pdotvrprm_pphi*(np.sqrt(Q) + 1) + Qprm_pphi*mur*pdotvr/(2*np.sqrt(Q)) + Qprm_pphi*(-nur*pdotvr + pdotn*xisq*(-mucostheta + nucostheta))/(2*np.sqrt(Q))) + Btilde**2*Jtilde*Sdotxi_rprm_pphi*(np.sqrt(Q)*(-nur*pdotvr + pdotn*xisq*(-mucostheta + nucostheta)) - mucostheta*pdotn*xisq + mur*pdotvr*(np.sqrt(Q) + 1)) + Btilde**2*Jtilde*Sdotxiprm_pphi*(-np.sqrt(Q)*(nur*pdotvr_r + nur_r*pdotvr + pdotn*xisq*(mucostheta_r - nucostheta_r) + pdotn_r*xisq*(mucostheta - nucostheta)) - mucostheta*pdotn_r*xisq - mucostheta_r*pdotn*xisq + mur*pdotvr_r*(np.sqrt(Q) + 1) + mur_r*pdotvr*(np.sqrt(Q) + 1) + Q_r*mur*pdotvr/(2*np.sqrt(Q)) + Q_r*(-nur*pdotvr + pdotn*xisq*(-mucostheta + nucostheta))/(2*np.sqrt(Q))) + Btilde**2*Jtilde_r*Sdotxi*(np.sqrt(Q)*(-nur*pdotvrprm_pphi + pdotnprm_pphi*xisq*(-mucostheta + nucostheta)) - mucostheta*pdotnprm_pphi*xisq + mur*pdotvrprm_pphi*(np.sqrt(Q) + 1) + Qprm_pphi*mur*pdotvr/(2*np.sqrt(Q)) + Qprm_pphi*(-nur*pdotvr + pdotn*xisq*(-mucostheta + nucostheta))/(2*np.sqrt(Q))) + Btilde**2*Jtilde_r*Sdotxiprm_pphi*(np.sqrt(Q)*(-nur*pdotvr + pdotn*xisq*(-mucostheta + nucostheta)) - mucostheta*pdotn*xisq + mur*pdotvr*(np.sqrt(Q) + 1)) + Btilde*Btilde_r*Jtilde*Sdotxi*(np.sqrt(Q)*(-2*nur*pdotvrprm_pphi + 2*pdotnprm_pphi*xisq*(-mucostheta + nucostheta)) - 2*mucostheta*pdotnprm_pphi*xisq + mur*pdotvrprm_pphi*(2*np.sqrt(Q) + 2) + Qprm_pphi*mur*pdotvr/np.sqrt(Q) + Qprm_pphi*(-nur*pdotvr + pdotn*xisq*(-mucostheta + nucostheta))/np.sqrt(Q)) + Btilde*Btilde_r*Jtilde*Sdotxiprm_pphi*(np.sqrt(Q)*(-2*nur*pdotvr + 2*pdotn*xisq*(-mucostheta + nucostheta)) - 2*mucostheta*pdotn*xisq + mur*pdotvr*(2*np.sqrt(Q) + 2))
    HsoTerm2_rprm_pphi = HsoTerm2a_rprm_pphi + HsoTerm2b_rprm_pphi - HsoTerm2c_rprm_pphi
    HsoTerm2coeff_rprm_pphi = expnu*(-Q_rprm_pphi - Q_rprm_pphi/(2*np.sqrt(Q)) + Q_r*Qprm_pphi/(4*Q**(3/2)))/(Btilde**2*exp2mu*xisq*(np.sqrt(Q) + Q)**2) + expnu*(-Q_r - Q_r/(2*np.sqrt(Q)))*(-2*Qprm_pphi - Qprm_pphi/np.sqrt(Q))/(Btilde**2*exp2mu*xisq*(np.sqrt(Q) + Q)**3) + expnu_r*(-Qprm_pphi - Qprm_pphi/(2*np.sqrt(Q)))/(Btilde**2*exp2mu*xisq*(np.sqrt(Q) + Q)**2) - exp2mu_r*expnu*(-Qprm_pphi - Qprm_pphi/(2*np.sqrt(Q)))/(Btilde**2*exp2mu**2*xisq*(np.sqrt(Q) + Q)**2) - Btilde_r*expnu*(-2*Qprm_pphi - Qprm_pphi/np.sqrt(Q))/(Btilde**3*exp2mu*xisq*(np.sqrt(Q) + Q)**2)
    HsoTerm1_rprm_pphi = SdotSkerrhat*exp2nu*pdotxir_rprm_pphi*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) + SdotSkerrhat*exp2nu*pdotxirprm_pphi*(-Btilde_r + expmu*expnu_r + expmu_r*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) - SdotSkerrhat*exp2nu*expmu_r*pdotxirprm_pphi*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu**2*xisq) + SdotSkerrhat*exp2nu_r*pdotxirprm_pphi*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) + SdotSkerrhat_r*exp2nu*pdotxirprm_pphi*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) + SdotSkerrhat_rprm_pphi*exp2nu*pdotxir*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) + SdotSkerrhatprm_pphi*exp2nu*pdotxir*(-Btilde_r + expmu*expnu_r + expmu_r*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) + SdotSkerrhatprm_pphi*exp2nu*pdotxir_r*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) - SdotSkerrhatprm_pphi*exp2nu*expmu_r*pdotxir*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu**2*xisq) + SdotSkerrhatprm_pphi*exp2nu_r*pdotxir*(-Btilde + expmu*expnu)/(Btilde**2*np.sqrt(Q)*expmu*xisq) - Q_r*SdotSkerrhat*exp2nu*pdotxirprm_pphi*(-Btilde + expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq) - Q_r*SdotSkerrhatprm_pphi*exp2nu*pdotxir*(-Btilde + expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq) - Q_rprm_pphi*SdotSkerrhat*exp2nu*pdotxir*(-Btilde + expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq) - Qprm_pphi*SdotSkerrhat*exp2nu*pdotxir*(-Btilde_r + expmu*expnu_r + expmu_r*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq) - Qprm_pphi*SdotSkerrhat*exp2nu*pdotxir_r*(-Btilde + expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq) + Qprm_pphi*SdotSkerrhat*exp2nu*expmu_r*pdotxir*(-Btilde + expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu**2*xisq) - Qprm_pphi*SdotSkerrhat*exp2nu_r*pdotxir*(-Btilde + expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq) - Qprm_pphi*SdotSkerrhat_r*exp2nu*pdotxir*(-Btilde + expmu*expnu)/(2*Btilde**2*Q**(3/2)*expmu*xisq) + Q_r*Qprm_pphi*SdotSkerrhat*exp2nu*pdotxir*(-3*Btilde + 3*expmu*expnu)/(4*Btilde**2*Q**(5/2)*expmu*xisq) - Btilde_r*SdotSkerrhat*exp2nu*pdotxirprm_pphi*(-2*Btilde + 2*expmu*expnu)/(Btilde**3*np.sqrt(Q)*expmu*xisq) - Btilde_r*SdotSkerrhatprm_pphi*exp2nu*pdotxir*(-2*Btilde + 2*expmu*expnu)/(Btilde**3*np.sqrt(Q)*expmu*xisq) + Btilde_r*Qprm_pphi*SdotSkerrhat*exp2nu*pdotxir*(-2*Btilde + 2*expmu*expnu)/(2*Btilde**3*Q**(3/2)*expmu*xisq)
    Hso_rprm_pphi = HsoTerm1_rprm_pphi + HsoTerm2*HsoTerm2coeff_rprm_pphi + HsoTerm2_r*HsoTerm2coeffprm_pphi + HsoTerm2_rprm_pphi*HsoTerm2coeff + HsoTerm2coeff_r*HsoTerm2prm_pphi
    Hd_rprm_pphi = Hdcoeff*Hdsum_rprm_pphi + Hdcoeff_r*Hdsumprm_pphi
    Hns_rprm_pphi = betapsum_rprm_pphi + Hnsradicand_rprm_pphi*alpha/(2*np.sqrt(Hnsradicand)) + Hnsradicandprm_pphi*alpha_r/(2*np.sqrt(Hnsradicand)) - Hnsradicand_r*Hnsradicandprm_pphi*alpha/(4*Hnsradicand**(3/2))
    Hs_rprm_pphi = Hso_rprm_pphi + Hss_rprm_pphi
    Heff_rprm_pphi = -Hd_rprm_pphi + Hns_rprm_pphi + Hs_rprm_pphi
    Hreal_rprm_pphi = -Heff_r*Heffprm_pphi*eta**2/(2*eta*(Heff - 1) + 1)**(3/2) + Heff_rprm_pphi*eta/np.sqrt(2*eta*(Heff - 1) + 1)
    return np.array([Hreal_rprm_pphi])